### PR TITLE
Update doc with new settings features

### PR DESCRIPTION
**Pull request by sandy081**
- New improvements to user/workspace settings
- Language specific editor settings

### CODE REVIEW

**Comment by sandy081** [comment]
@gregvanl I could not update/upload the gif in Default settings section due to the space limitations. I see the existing gif is stored remotely. Not sure how can I upload there.

Thanks

**Comment by gregvanl** [comment]
Thanks! @waderyan can help upload the update .gif.

**Comment by waderyan** [comment]
@sandy081 the uploads are in azure blob called vscodevideos. LMK if you don't have access and I can help you out. Its under our Ticinio subscription.

**Comment by sandy081** [comment]
@waderyan Can you give me the location of vscodevideos so that I can check if I have access to it

**Pull request merged**
