### PR TITLE
Document Remote-Containers adoption of workspace trust

### PR DESCRIPTION
**Pull request by bamurtaugh**
Fixes https://github.com/microsoft/vscode-docs/issues/4580

@chrmarti @Chuxel I created a separate "Trusting your Workspace" section after the various sections about opening folders and cloning repos into volumes since users would run into workspace trust at/by this point. 

Another flow I thought of was adding the workspace trust points to each affected section (i.e. rather than an entire "Trusting your Workspace" section, add a description to the reopening folder section, cloning volume section, inspecting volume section, etc.). But I wasn't sure if this would feel repetitive and if it'd make more sense to keep all of the workspace trust in one section. 

Let me know your thoughts on location, wording, etc! Happy to adjust since I wasn't sure which flow would work best (or if another flow/location entirely might be better).

### CODE REVIEW

**Comment by chrmarti** [comment]
Having all in one place looks good to me.

**Review by chrmarti — APPROVED** [review]

**Comment by Chuxel** [comment]
LGTM - Though one question. Do we want to cross reference to the remote extensions from the main workspace trust article as well?

As Codespaces factors this in, there's a similar consideration there.

**Review by Chuxel — APPROVED** [review]

**Comment by gregvanl** [comment]
This will go live once Workspace Trust is available in Stable so labeling with `don't merge` for now.

**Comment by bamurtaugh** [comment]
Thanks for the reviews! @Chuxel I could see that being useful (since remote and trusting remotes could be a potentially big topic in the realm of workspace trust).

In reviewing the main Workspace trust doc, I'm trying to envision where it might make sense. Maybe somewhere like https://code.visualstudio.com/docs/editor/workspace-trust#_trusting-a-workspace since it describes "If you trust the authors and maintainers of a project, you can trust the project's folder on your local machine," and we could reference somewhere in/right at the end of this section that this also applies to trusting from a remote/in remote workflows?

**Comment by chrmarti** [comment]
@bamurtaugh I'm adding `https://aka.ms/vscode-remote-containers-trust` to use on a Learn More button on the dialogs. Could you update that once this has gone live? Currently linking to the content of this PR, hope that's ok for Insiders.

Posted updated screenshots: https://github.com/microsoft/vscode-remote-release/issues/5136#issuecomment-854534310

**Comment by bamurtaugh** [comment]
@chrmarti Sounds good! I took note of this to remind me, so when we merge in this PR, I'll update the aka.ms link to the live link rather than the PR.

I also updated this PR with the latest screenshots ("Got it" phrasing).

**Pull request merged**
