### PR TITLE
Update dev container doc based on feedback

### PR DESCRIPTION
**Pull request by bamurtaugh**
Fixes https://github.com/microsoft/vscode-docs/issues/6094.

@chrmarti @hediet thanks for sharing this feedback, it makes a lot of sense to me too. 

I agree just listing 3 quick starts may be confusing or overwhelming, i.e. which do I pick? Do I need to complete them all in order? I added a `## Picking your quick start` section at the top to provide further context. I also numbered each quick start as that feels a bit easier to parse (I can quickly see there are 3 quick starts, rather than not knowing if there are 1, 5, 10, or more).

I removed the [Working with Containers](https://code.visualstudio.com/docs/devcontainers/containers#_working-with-containers) header as it felt confusing to have this so early and feels like it may direct users to leave the page. I moved its couple of sentences to the top of the doc in the existing top intro section.

I also added a screenshot of the template picker to the "Create a devcontainer.json file" section, and reordered that section so that the template picker comes first, rather than it appearing that users should be hand creating their devcontainer.json.

Let me know if you have other feedback!

cc @Chuxel

### CODE REVIEW

**Review by Chuxel — APPROVED** [review]

**Comment by bamurtaugh** [comment]
@chrmarti @hediet please just let me know if you have any feedback, thanks so much!

**Review by chrmarti — APPROVED** [review]
I wonder if it would make sense to move the architecture diagram further down because that is not what potential new users are looking for, they are usually more interested in the Quick Starts and the prerequisites. Maybe something to think about first.

LGTM!

**Comment by bamurtaugh** [comment]
That's great feedback @chrmarti - I'll make a note of that since it's how we generally structure our remote docs.

@gregvanl this is ready for your review and merge whenever you have a chance, thanks!

**Review by gregvanl — APPROVED** [review]
Looks good

**Pull request merged**
