### PR TITLE
Fix invalid statements in ASP.NET 5 Runtime doc

### PR DESCRIPTION
**Pull request by scottaddie**
This PR addresses issue https://github.com/Microsoft/vscode-docs/issues/63. There were some inaccurate statements in the ASP.NET Runtime page's "Projects and Project Selection" section.

### CODE REVIEW

**Comment by scottaddie** [comment]
@gregvanl I like it. This seems to flow a bit better. I'll work on updating the PR.

**Comment by scottaddie** [comment]
@gregvanl How does it look now?

**Comment by pali88** [comment]
pr update

**Comment by gregvanl** [comment]
No worries, I'll fix the typo myself.
We're in the process of updating our code.visualstudio.com portal tooling so this won't go to the live site for a couple of days.

**Comment by scottaddie** [comment]
Thank you, @gregvanl.

**Pull request merged**
