### PR TITLE
Relative Variable Substitution

### PR DESCRIPTION
**Pull request by adstep**
adding support for substituting the current opened file relative to cwd

### CODE REVIEW

**Comment by gregvanl** [comment]
@adstep I'll hold on this PR until the corresponding PR in vscode goes live in the next release. 
One option is to move this PR to vscode-docs vnext branch where we do our prerelease documentation.  Before each monthly release, the team updates the release notes and main docs in vnext and then we merge all the doc changes to master on the day of the release and republish the website.

**Comment by adstep** [comment]
Thanks @gregvanl. This is my first time contributing so I'm unfamiliar with the process.

Corresponding PR: https://github.com/Microsoft/vscode/pull/8982

Should I just drop this PR and create a new one for the vscode-docs branch?

**Comment by gregvanl** [comment]
This is such a small change, I can manually port it to vscode-docs vnext once the vscode PR is accepted.  Let's just use the current PR for tracking and the final content.

**Comment by gregvanl** [comment]
Ported to vscode-docs vnext branch with https://github.com/Microsoft/vscode-docs/commit/097191dd108a445358b96f17818a67596bce2822

**Pull request closed without merging**
