### PR TITLE
Update java-tutorial.md

### PR DESCRIPTION
**Pull request by rcouch00**

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @rcouch00, Thank you for your interest in our documentation and the PR. The Java tutorial should work on Windows, Linux and macOS and isn't Windows specific so closing this PR. VS Code runs on all three platforms so please let us know if their is any platform specific content that needs to be added.

**Comment by rcouch00** [comment]
It doesn't work on mac, clone the repo, navigate to Application.java and VS Code hangs at 100% Starting Java Language Server - Refreshing '/jdt.ls-java-project'.

Other projects are fine, I have other java samples working.  I tried to clear all the workspace settings, re clone the repo, still doesn't work.

"Should"™ but Doesn't

**Comment by gregvanl** [comment]
@rcouch00 Thanks for following up with details.
@hexiaokai Have you been able to use the tutorial repo on macOS? Do you think this is a documentation issue or related to one of the Java extensions?

**Comment by testforstephen** [comment]
@rcouch00 Did you run the tutorial on JDK 9?

The spring boot project on tutorial is using gradle-2.13, it has a known issue about java 9 support. You should manually update the gradle-wrapper.properties to 4.4.

Find these two files:
https://github.com/spring-guides/gs-spring-boot/blob/master/complete/gradle/wrapper/gradle-wrapper.properties
https://github.com/spring-guides/gs-spring-boot/blob/master/initial/gradle/wrapper/gradle-wrapper.properties

Update `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-bin.zip`

**Pull request closed without merging**
