### PR TITLE
docs: variables-reference.md include settings.json

### PR DESCRIPTION
**Pull request by janosh**
-  make it clear that besides `launch.json` and `tasks.json`, variable substitution is also available in `settings.json`

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @janosh Thank you for your interest in the VS Code documentation and taking the time to submit a PR. The variables enumerated in the Variables Reference topic are not available for settings.json. There are some variables for some settings, such as for windows.title, but these are setting specific and not the general launch.json and task.json shared variables.

**Comment by janosh** [comment]
That's weird. I used `${workspaceFolder}` in `settings.json` as described in [this comment](https://github.com/microsoft/vscode-python/issues/5840#issuecomment-497321419) and it's definitely working. This information would have been valuable so even if only some variables are supported in `settings.json` I think it would be worth listing those.

**Comment by gregvanl** [comment]
In the example you show, ${workspaceFolder} is passed as a string to the Python extension to evaluate and the extension knows how to expand ${workspaceFolder}. The variable is not expanded by VS Code through its own settings. The Variable Reference topic shows which variables will be evaluated by the VS Code debugger and task features.

**Comment by janosh** [comment]
Oh I see, sorry for the confusion.

**Pull request closed without merging**
