### PR TITLE
Workbench colors documentation

### PR DESCRIPTION
**Pull request by aeschli**
For the workbench theming effort we now allow to configure a large set of colors.
These colors can be set in color themes as well as in the user settings (under `"workbench.colorCustomizations"`).

This is my attempt of documenting these colors.
The list is currently in https://github.com/Microsoft/vscode-docs/blob/vnext/docs/getstarted/themes.md#L70 but I guess this adds too much content to that doc. My PR creates a new page, but I would let @gregvanl decide where to include it.

@bpasero Feel free to fix & add more information / screenshots

### CODE REVIEW

**Comment by gregvanl** [comment]
@aeschli Excellent, I was just looking at the new content in themes.md and thought it was too much for a Get Started topic. I think this could go in a Customizing Themes topic under User Guide.

**Comment by gregvanl** [comment]
@aeschli Now that I see that the content is just a reference, I've gone with a file under /docs/getstarted that isn't in the TOC which we can link to and can be found in search.

**Comment by bpasero** [comment]
Very cool 👍

**Comment by aeschli** [comment]
Great, thanks @gregvanl !
I'm going to link to it from the release notes.

**Comment by gregvanl** [comment]
@aeschli I believe I already did. The link won't work until we actually publish the new topic live. We have to use absolute URL links for the in-product release notes.

**Pull request merged**
