### PR TITLE
Clarify dev container CLIs

### PR DESCRIPTION
**Pull request by bamurtaugh**
Refer to the current "`devcontainer` CLI" as the "VS Code `devcontainer` CLI", to differentiate from the [reference implementation CLI](https://github.com/microsoft/dev-container-spec/issues/9).

@Chuxel @chrmarti Would love any thoughts or feedback! i.e. on the new naming, mentioning the reference implementation at this point or in this way.

### CODE REVIEW

**Review by Chuxel — APPROVED** [review]

**Comment by Abrdjalw** [comment]
Duplicate of #

**Review by chrmarti — APPROVED** [review]
LGTM! We can think about renaming it from `devcontainer` to `remotecontainer` or similar. Something to look into after we have the reference implementation CLI.

**Comment by bamurtaugh** [comment]
Thank you both for the reviews!

@chrmarti that's a good idea - opened https://github.com/microsoft/vscode-remote-release/issues/6424 to track (let me know if we should track elsewhere, like dev-container-spec repo).

@gregvanl This is ready for your review and merge!

**Comment by felipecrs** [comment]
> LGTM! We can think about renaming it from `devcontainer` to `remotecontainer` or similar. Something to look into after we have the reference implementation CLI.

Or its functionalities could be added to the VSCode's `code` CLI (which of course would require the VSCode itself to expose APIs for making it possible for an extension to contribute features to the CLI).

And then:

```
$ cd my-repo
$ code --remote-container .
```

Considering that `build` would not be required by it, as it would be in the open-source `devcontainer` instead.

**Pull request merged**
