### PR TITLE
Use LF as the line-ending character consistently

### PR DESCRIPTION
**Pull request by luangong**
Developers from different operating systems are facing inconsistent line endings all the time, which cause a lot of pain.

This commit replaces all CRLFs with LFs to follow [vscode](https://github.com/microsoft/vscode)'s [convention](https://github.com/microsoft/vscode/blob/master/.vscode/settings.json) using GNU find and [dos2unix](https://waterlan.home.xs4all.nl/dos2unix.html):

```bash
find . -regextype posix-extended -iregex '.*\.(css|js|json|lock|md)' -exec dos2unix {} \;
```

or, if you are using BSD find on macOS, issue the following command instead:

```bash
find -E . -iregex '.*\.(css|js|json|lock|md)' -exec dos2unix {} \;
```

The new settings in `.vscode/settings.json` and `.editorconfig` also enforce the use of LF as the line-ending character in future commits.

People working on this repo may need to resolve conflicts introduced by this PR by using one of the above mentioned commands.

@gregvanl Don’t be scared by the big red and green blocks. I only changed the line-ending characters. Everything else remains the same.

### CODE REVIEW

**Comment by octref** [comment]
Thanks for the PR! Do you mind rebasing this on current master?

**Comment by gregvanl** [comment]
@luangong Thanks for responding so quickly. Can you rebase again? We'll wait until you are done before making any other changes.

**Comment by luangong** [comment]
I’m resolving merge conflicts. I’ll let you know once I’m done.

**Comment by luangong** [comment]
Done.

**Comment by gregvanl** [comment]
Thanks!

**Pull request merged**
