### PR TITLE
Fix numbering under "Build the program" section.

### PR DESCRIPTION
**Pull request by michelleangela**
Fix numbering of last step of "Build the program".

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @michelleangela Want to fix https://code.visualstudio.com/docs/cpp/config-msvc#_start-vs-code-from-the-developer-command-prompt as well?

**Comment by gregvanl** [comment]
Also https://code.visualstudio.com/docs/cpp/config-clang-mac#_build-the-program

**Comment by michelleangela** [comment]
Thanks for pointing out the other numbering issues. Added the fix.

**Comment by gregvanl** [comment]
Thanks!

**Pull request merged**
