### PR TITLE
Update built-in commands

### LINKED ISSUE #5826: Document type call hierarhcy API for built-in commands
According to https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostApiCommands.ts, `type callhiearchy` is a new built-in command, but seems [vscode document](https://code.visualstudio.com/api/references/commands) didn't mention it.

Maybe we can add it to document?

### PR DESCRIPTION
**Pull request by chouzz**
This patch improve built-in commands description, including:

- Update description for call hierarchy since https://github.com/microsoft/vscode/issues/167717 fixed
- Add new API description for `type hierarchy`
- Update other APIs according to [API file](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostApiCommands.ts)

fix #5826

### CODE REVIEW

**Comment by chouzz** [comment]
@microsoft-github-policy-service agree

**Comment by gregvanl** [comment]
Hi @chouzz, we're getting ready for a release this week so a little slow looking at PRs. Thanks for your patience

**Comment by chouzz** [comment]
No problem.

**Review by gregvanl — APPROVED** [review]
Thanks!
Sorry for the delay

**Pull request merged**
