### PR TITLE
docs: remove example reference from faq section

### LINKED ISSUE #5380: Remove [Unsupported] references in supporting/faq
In the milestone https://github.com/microsoft/vscode/issues/151104 is done the docs will need an update: https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

### PR DESCRIPTION
**Pull request by Evavic44**
Example reference from https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported removed. 
Fixes #5380

### CODE REVIEW

**Comment by gregvanl** [comment]
Adding 'don't merge' label as product change moved to July milestone

**Review by Tyriar — APPROVED** [review]
Thanks @Evavic44, this wasn't exactly what I was after since my issue wasn't described properly. I made the tweak to get rid of references to the title bar specifically as unsupported will still be a concept.

**Comment by Tyriar** [comment]
@gregvanl we should merge this after the v1.69 `vnext` gets merged into `main`. The VS Code side changes have happened on `main`.

**Comment by Evavic44** [comment]
> Thanks @Evavic44, this wasn't exactly what I was after since my issue wasn't described properly. I made the tweak to get rid of references to the title bar specifically as unsupported will still be a concept.

Oh! So sorry about the confusion. Thanks for clarifying it.

**Pull request merged**
