### PR TITLE
Update document to use Azure Functions

### PR DESCRIPTION
**Pull request by pragnagopa**
Update document to use Azure Functions instead of serverless

### CODE REVIEW

**Comment by pragnagopa** [comment]
@hexiaokai @rloutlaw @asavaritayal

**Comment by kyliel** [comment]
Looks good for me. Though I am the back up of Xiaokai during his vacation but I don't have the approval right for this doc. @rloutlaw, can you approve it? Thanks.

**Comment by YoRobotCop** [comment]
Gracias Microsoft Team

**Comment by gregvanl** [comment]
@pragnagopa I've added the redirect from https://code.visualstudio.com/docs/java/java-serverless to go to https://code.visualstudio.com/docs/java/java-azurefunctions.

**Comment by pragnagopa** [comment]
Thanks 👍

**Pull request merged**
