### PR TITLE
Added Content Provider tutorial and example

### PR DESCRIPTION
**Pull request by l7ssha**
Hi, I've created tutorial and example code for Content Provider.
For last week I was working on my extensions project and for me this part of API was very confused, so I decided to write some text for others. 

Point me mistakes in text, and grammatical problems - I'm not native english. Also this is my first tutorial written. I'll fix all of those.

### CODE REVIEW

**Comment by jrieken** [comment]
Looks reasonable but you should know that we are working on a replacement for the previewHtml-command, make this guide then somewhat obsolete or less important.

**Comment by l7ssha** [comment]
@jrieken for now we have to use htmlPreview. When you release replacement for this I will fix guide

**Comment by jrieken** [comment]
Please don't document the webview yet. Everything is still up in the air, mostly likely to change, and not available to extensions that are being published.

**Comment by l7ssha** [comment]
So, I removed this, I'll update when it will be ready.

**Comment by gregvanl** [comment]
@l7ssha I'll work on getting this merged and published today. Thanks.

**Comment by gregvanl** [comment]
@l7ssha I'm doing an edit pass now and I'll reply here when the tutorial is published.

**Comment by gregvanl** [comment]
@l7ssha I had to make quite a few edits and some source code changes (for example activating the extension on "*" is an anti-pattern that we don't want to encourage). I've published the tutorial and you can review it on https://code.visualstudio.com/docs/extensions/example-content-provider. I've pulled it out of the TOC until you've had a chance to review my changes. Let me know if I've gone too far and if you'd like changes (you can reply here or submit another PR).

**Comment by l7ssha** [comment]
Looks good, I forgot to reply, but however :D

**Pull request merged**
