### PR TITLE
Made it clearer this is just for Linux containers

### PR DESCRIPTION
**Pull request by gabrielmccoll**
I think it's easy to miss as it is now and there will be an idea that it will work since it's Windows and it's Microsoft.

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @gabrielmccoll Good idea for the clarification. To keep the first paragraph flow general, I'd rather not add the Linux qualifier there but think it's a great idea to add your clarification on the first mention of Windows. Can you change that sentence to read "Windows container images are not supported"? Thanks

**Comment by gabrielmccoll** [comment]
Love to yep did think that was maybe too much.  First time doing this so not sure how to change and try again .

**Comment by gabrielmccoll** [comment]
Think I did it @gregvanl

**Comment by gregvanl** [comment]
Perfect. Thanks!

**Pull request merged**
