### PR TITLE
[WIP] saying more about pip freeze

### LINKED ISSUE #1967: Talk about the problems on using pip freeze
Hello all, how are you? I was reading the docs on Django and Flask, and on both of them are saying to use ```pip freeze > requirements.txt```. That's good for explaining how a requirements file works, but its not the best practice, since you can create a requirements file full of packages that are not needed for the specific project. Besides, we could talk more about versions of packages inside the file. 
What do you think? Thanks a lot!

### PR DESCRIPTION
**Pull request by Guilhermeslucas**
This is just a draft of what I'm thinking about to put at docs.
Fixes #1967 .

### CODE REVIEW

**Comment by kraigb** [comment]
Thanks--see what you think of my recent edit here. I think the caveat is best pulled out into a side note, where we can also include a link to the requirements.txt docs. If this works for you, copy it to the same place in the tutorial-django.md file.

**Comment by Guilhermeslucas** [comment]
I loved your changes @kraigb . I'll put it just like this on Django docs too!

**Comment by kraigb** [comment]
Great, do that and I'll merge in.

**Comment by Guilhermeslucas** [comment]
Just did it!

**Comment by kraigb** [comment]
Please note the CLA signing that's needed above.

**Comment by Guilhermeslucas** [comment]
Just did it @kraigb :)

**Comment by kraigb** [comment]
Great--thanks for your help!

**Comment by Guilhermeslucas** [comment]
Thanks for it, man! Keep rocking!

**Pull request merged**
