### PR TITLE
Add release notes for Jupyter extension

### PR DESCRIPTION
**Pull request by rchiodo**

### CODE REVIEW

**Review by rebornix — APPROVED** [review]

**Review by amunger — APPROVED** [review]

**Review by greazer — COMMENTED** [review]
Looks good, though isn't there some extra knowledge/actions.involved if trying to connect to https? If so, we could add an item to Discussions that we can reference here.

**Review by greazer — COMMENTED** [review]
Actually we should probably just have a single Discussion item that indicates some of the limitations for what's here. 

This includes, ipywidget support isn't full yet, variable viewing doesn't support dataframe viewing, interactive window doesn't support debugging. 

Anything else?

**Comment by rchiodo** [comment]
Intellisense doesn't work. Although we're not really providing it anymore.

**Comment by rchiodo** [comment]
Extra actions for https are only when creating a https server on your own with an invalid certificate. The browser won't accept connections to that. There's a wiki page about it that we could mention in the discussion item.

**Comment by rchiodo** [comment]
I'll add a discussion item and link to it in the release notes.

**Comment by rchiodo** [comment]
Oh looks like you did that already.

**Comment by greazer** [comment]
> 

Yeah, and am in the middle of trying to juggle a mac and a pc, so if you want to edit what I started, feel free.

**Pull request merged**
