### PR TITLE
Fix capitalization of GitHub org

### PR DESCRIPTION
**Pull request by friederbluemle**
`github.com/Microsoft` -> `github.com/microsoft`

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @friederbluemle Thank you for the PR. 
MicrosoftDocs is correctly cased so please revert those changes.
https://github.com/MicrosoftDocs/vsonline

**Comment by friederbluemle** [comment]
> Hi @friederbluemle Thank you for the PR.
> MicrosoftDocs is correctly cased so please revert those changes.
> [MicrosoftDocs/vsonline](https://github.com/MicrosoftDocs/vsonline)

Nice catch! I'll fix it.

**Comment by friederbluemle** [comment]
Resolved conflicts, rebased, and addressed comment.

**Comment by gregvanl** [comment]
Thanks

**Pull request merged**
