### PR TITLE
Add static website deploy tutorial

### PR DESCRIPTION
**Pull request by bowdenk7**
Still need to add a section that includes Travis, but I think this is good enough to start reviewing.

[Hosted here](http://staticsite-tutorial.azurewebsites.net/tutorials/static-website/getting-started ) for easier reviewing.

### CODE REVIEW

**Comment by gregvanl** [comment]
Added 'don't merge' label while this is under review.

**Comment by chrisdias** [comment]
Can't you just remove that file from the PR? it probably got built while running the site...

**Comment by gregvanl** [comment]
The API reference topic is auto-generated and it isn't a big deal if we merge your changes in since we can do a baby build afterwards to regenerate it before we publish live.

**Comment by bowdenk7** [comment]
@gregvanl, @fiveisprime, @kennethkau, @DanielRosenwasser - anyone get a chance to review this? Would love to get these published.

**Comment by gregvanl** [comment]
@bowdenk7 Let me know when the technical content has been reviewed by others and then I can do an edit/conventions pass.

**Pull request merged**
