### PR TITLE
Fixes #2702

### LINKED ISSUE #2702: Uneccesary <p></p> tags in Django Tutorial
I was looking through the Django Tutorial as I am currently thinking of switching to using VS Code instead of Pycharm, and I noticed in [this section](https://github.com/microsoft/vscode-docs/blob/63214cd2616f9edca20adefe4593859617720b78/docs/python/tutorial-django.md#use-the-code-snippet-to-add-pages) that it instructs users to enter `<p>Home page for the Visual Studio Code Django tutorial.</p>` in the `{% block title %}` section, but the `<p><\p>` tags are not necessary because the `{% block title %}` section is already included inside of the `<title></title>` tags in the template. Doing as instructed, the `<p></p>` tags are rendered in the tab header as plain text.

### PR DESCRIPTION
**Pull request by endormi**
I fixed Flask's issues as well.

### CODE REVIEW

**Comment by endormi** [comment]
Hmmm, is there a reason why you haven't merged my PR? @gregvanl jus wondering, since it is a fix.

**Comment by gregvanl** [comment]
Hi @endormi The python tutorials are owned by another writer but it looks like @JoshuaPartlow is currently out. I'll try to have a look at your PR shortly. Sorry for the delay.

**Comment by endormi** [comment]
Great, thanks!

**Comment by gregvanl** [comment]
Hi @endormi, I had a look at issue #2702 and the Python Django tutorial and I think the issue creator was confused and put the paragraph into the title block rather than the content block. I'm not sure this PR is necessary. While the <p> aren't strictly necessary, they do force a new line before displaying the content.

**Comment by endormi** [comment]
@gregvanl I can do a quick fix, adding the tags inside {% block content %]

**Comment by gregvanl** [comment]
Also looking quickly at Django documentation, it looks like the convention is to use HTML tags within elements inside content blocks.

**Comment by endormi** [comment]
Okay, that's fine 👍

**Comment by gregvanl** [comment]
Thanks again for taking the time to submit a PR!

**Comment by endormi** [comment]
@gregvanl No problem! I'll be looking for possible fixes.

**Pull request closed without merging**
