### PR TITLE
Update with the latest pics and a new url for Azure Spring Apps

### PR DESCRIPTION
**Pull request by silenceJialuo**

### CODE REVIEW

**Comment by silenceJialuo** [comment]
@gregvanl Hi, Greg , There are some updates of Azure Spring Apps for you review.

First, I have updated all the pics related to the Deployment of Azure Spring Apps on VS Code.

Second, since the Azure Spring Cloud has been renamed to Azure Spring Apps, I think the file _java-spring-cloud.md_ should be renamed to _java-spring-apps.md_ . So I have renamed the file together with other links pointing to it.

Would you please save time to merge my PR? Feel free to contact me if any changes. Thanks in advance.

**Comment by silenceJialuo** [comment]
@gregvanl Hi Greg, thanks for your advice and I have changes all the screenshots related and pushed my PR again.

The last thing I want to confirm with you that, since I want to show the url for this page with "java-spring-apps" rather than "java-spring-cloud", I have renamed the file  _java-spring-cloud.md_ into _java-spring-apps.md_ as well as other links pointing to it. Considering the url with "java-spring-apps", is there anything else I need to change? Or you could modify them directly.

Thanks in advance.

**Comment by gregvanl** [comment]
Hi @silenceJialuo I will need to add a redirect from java-spring-apps to java-spring-cloud. I should be able to do this later today when after I merge your PR just before I publish the changes.
Thanks for updating the images!

**Comment by gregvanl** [comment]
@silenceJialuo Also there seems to be conflicts with this PR that need to be resolved before I can merge it. Is your fork and branch, up to date with upstream/main?

**Comment by silenceJialuo** [comment]
Hi @gregvanl , I have modified the branch into up to date with upstream/main. Thanks for your help!

**Comment by gregvanl** [comment]
Redirect has been added and updates published

**Comment by silenceJialuo** [comment]
Well noted. Thanks

**Pull request merged**
