### PR TITLE
Updated intro videos page.

### PR DESCRIPTION
**Pull request by bgashler1**
Must be merged in tandem with its brother PR on the vscode-website repo.

### CODE REVIEW

**Comment by bgashler1** [comment]
For https://github.com/Microsoft/vscode-website/issues/446

**Comment by waderyan** [comment]
Did you try this on different browsers?

**Comment by waderyan** [comment]
Code looks good.

**Comment by bgashler1** [comment]
@waderyan yes this works in all browsers.

**Pull request merged**
