### PR TITLE
Update "Configure IntelliSense for cross-compiling"

### PR DESCRIPTION
**Pull request by sean-mcmanus**
Part of microsoft/vscode-cpptools#10235 .

### CODE REVIEW

**Review by gregvanl — APPROVED** [review]
Thanks!

**Review by AlexandraKemperMS — APPROVED** [review]
The same feedback as with the other PR applies here for the github discussion/issues section, otherwise this looks good.

**Comment by sean-mcmanus** [comment]
> The same feedback as with the other PR applies here for the github discussion/issues section, otherwise this looks good.

@AlexandraKemperMS I fixed that -- let me know if you're still seeing an issue.

**Review by AlexandraKemperMS — APPROVED** [review]
I see the change, good to go!

**Review by gregvanl — APPROVED** [review]

**Pull request merged**
