### PR TITLE
Update python/debugging.md debugOptions

### PR DESCRIPTION
**Pull request by Tim113**
The changes to `debugOptions` in https://github.com/Microsoft/vscode-python/issues/1326 (which are reflected in the behaviour of my install of VS Code so I assume have been incorporated into the main debugger) do not appear to be reflected in the documentation.  This was causing me some problems.

So have updated the file to reflect them.

### CODE REVIEW

**Comment by Tim113** [comment]
image

**Comment by kraigb** [comment]
@Tim113 Thanks so much for catching these details, and for digging into the changes in the extension.

**Comment by kraigb** [comment]
@Tim113 Can you also sign the CLA in this PR? We need that in order to do the merge. Thanks.

**Comment by brettcannon** [comment]
This will most likely help with #2561 .

**Comment by kraigb** [comment]
Yes, Brett, the additions I've made to this PR will close 2561.

**Comment by kraigb** [comment]
@Tim113 We can't merge this PR until you sign the CLA. Please do this right away, otherwise I need to make the change in a different PR and close this one without merging.

**Comment by kraigb** [comment]
Closed due to inactivity; edits were included in a different PR.

**Pull request closed without merging**
