### PR TITLE
Adds relative link fix for several videos.

### LINKED ISSUE #5717: Links to Languages/JS videos broken
Videos at https://code.visualstudio.com/docs/languages/javascript lead to broken links. Have tested on multiple browsers and networks to ensure it's not a me problem.

For example, both of the broken links are rendered to the page:

- /assets/docs/languages/docs/languages/javascript/intellisense.mp4
- /assets/docs/languages/docs/languages/javascript/snippets.mp4

Based on examining `.gif` files on the R page it appears they should lead to these links (boom, there the files are!):

- /assets/docs/languages/javascript/intellisense.mp4
- /assets/docs/languages/javascript/snippets.mp4

In other words, the extra "docs/languages/" must be removed from the links.

### PR DESCRIPTION
**Pull request by anthonyisensee**
I don't know exactly how your website build occurs but based on other /assets/ links present in the repository I believe this should fix the broken video links and point to the files that are actually there. May fix #5717.

### CODE REVIEW

**Comment by anthonyisensee** [comment]
@microsoft-github-policy-service agree

**Comment by gregvanl** [comment]
@anthonyisensee I've discussed a different solution in the issue. Would you like to update your PR?

**Comment by anthonyisensee** [comment]
@gregvanl I believe these changes implement your [request](https://github.com/microsoft/vscode-docs/issues/5717#issuecomment-1284323169). Thanks for the guidance!

**Review by gregvanl — APPROVED** [review]
Thanks!

**Pull request merged**
