### PR TITLE
Add languages guide for Ruby

### PR DESCRIPTION
**Pull request by vinistock**
Add a guide for the Ruby language in VS Code. The entry explains how to set up and use the Ruby LSP and is very similar to the Rust docs.

cc @isidorn

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @vinistock Thank you for submitting a PR, I haven't done a full review but I noticed that you are committing the images as binary files. 
The vscode-docs repo uses Git LFS (Large File System) to avoid committing large image and video files to the repo. You can learn how to install and enable Git LFS in https://github.com/microsoft/vscode-docs/blob/main/README.md#cloning.

Can you either update this PR or create a new PR with Git LFS enabled in your local forked repo? Thanks

**Comment by vinistock** [comment]
Followed the steps to setup LFS for my local fork and made the commit again.

**Review by gregvanl — APPROVED** [review]
Looks really good. Thanks!

I'll do a follow up PR for some small edits and formatting and to fill in the missing metadata.

**Comment by vinistock** [comment]
Thank you! We weren't sure how to fill the metadata indeed.

**Comment by gregvanl** [comment]
Here's the follow up PR that we just merged https://github.com/microsoft/vscode-docs/pull/6159
I moved the topic up in the TOC between R and Rust, `cause why not?
We should be able to publish today. Thank you again!

**Comment by vinistock** [comment]
Amazing. Thanks again!

**Comment by gregvanl** [comment]
Apologies, it looks like the new topic won't go live until Monday (a few website updates in progress)

**Comment by gregvanl** [comment]
Published at https://code.visualstudio.com/docs/languages/ruby
We'll give this new topic a mention in the next 1.77 release notes in the "Documentation" section

**Comment by gregvanl** [comment]
@vinistock Readers are happy

image

**Pull request merged**
