### PR TITLE
First pass on VS Code at build blog post.

### PR DESCRIPTION
**Pull request by gregvanl**

### CODE REVIEW

**Comment by egamma** [comment]
@waderyan @gregvanl @chrisdias  there was more about Code in other sessions that should be covered: 

* C++ extension for Code demoed in https://channel9.msdn.com/Events/Build/2016/C-Discussion starts at 3'
* node time travel debugging demoed in https://channel9.msdn.com/Events/Build/2016/B870 at 39'
* C# debugging in https://channel9.msdn.com/Events/Build/2016/B889 at 39'

I also wonder whether the react native or cordova extensions where demoed in other sessions.

**Comment by gregvanl** [comment]
VS Code was used in the Cordova and Ionic talk https://channel9.msdn.com/Events/Build/2016/B835 but debugging didn't work so I was going to be quiet about that one.

**Comment by egamma** [comment]
- C# debugging was demoed in `the future of C#` talk and it worked well, pls see minute 39 of https://channel9.msdn.com/Events/Build/2016/B889 
- Node debugging in VS Code got a lot of coverage in this this talk `Node.js and Microsoft: A Love Story about Developer Tools` and it deserves to be mentioned

**Comment by waderyan** [comment]
This sounds great to me.

**Comment by waderyan** [comment]
@gregvanl it doesn't look like I have edit rights... can you make the changes are add me to your forked repo?

**Comment by gregvanl** [comment]
@waderyan I can make the edits.  If everyone is happy, can I publish today?

**Comment by waderyan** [comment]
Yeah definitely :)

**Pull request merged**
