### PR TITLE
make workspace extensions explanation consistent

### LINKED ISSUE #6046: Inconsistent explanation of Workspace Extensions
In the "Supporting Remote Development and GitHub Codespaces" [page](https://code.visualstudio.com/api/advanced-topics/remote-extensions#common-problems), Workspace Extensions are explained to be able to run on the local Extension Host and the remote Extension Host: 
image

but a later part of that page says "Workspace Extensions are run in a Remote Extension Host that sits in a small VS Code Server" without clarifying that happens when it is in a remote workspace:
image

### PR DESCRIPTION
**Pull request by danBamikiya**
Resolves #6046 

before edit:

image

after edit:

image

### CODE REVIEW

**Review by gregvanl — APPROVED** [review]
Thanks, apologies for the delay

**Comment by danBamikiya** [comment]
@gregvanl no problem!

**Comment by gregvanl** [comment]
@danBamikiya Your change went live on Friday but unfortunately website issues caused us to roll back the last deployment. Not related to your topic update but just wanted to give you a heads up that your change won't go live until we get the website issues sorted out.

**Comment by danBamikiya** [comment]
thanks for the heads up @gregvanl I really appreciate it!

**Pull request merged**
