### PR TITLE
debug actions into a table with corresponding explanations

### PR DESCRIPTION
**Pull request by mavaddat**
The debug actions need a bit of elaboration for any beginner.

### CODE REVIEW

**Comment by mavaddat** [comment]
@gregvanl @lramos15 Can I request a review of this PR?

**Comment by gregvanl** [comment]
Hi @mavaddat Sorry for the delay. I like the suggestion of using a table. We'll try to get this reviewed this week. Thanks

**Comment by mavaddat** [comment]
The table I added looks like this:

| Action                                                 | Explanation                                                                                                                                                            |
|--------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Continue / Pause `kb(workbench.action.debug.continue)` | Either <ul><li> *Continue*: Resume normal program/script execution (up to the next breakpoint), or</li> <li> *Pause*: Inspect code executing at the current line and debug line-by-line</li></ul>     |
| Step Over `kb(workbench.action.debug.stepOver)`        | Execute the next method as a single command without inspecting or following its component steps                                                                    |
| Step Into `kb(workbench.action.debug.stepInto)`        | Enter the next method to follow its execution line-by-line                                                                                                         |
| Step Out `kb(workbench.action.debug.stepOut)`          | When inside a method or subroutine, return to the earlier execution context by completing remaining lines of the current method as though it were a single command |
| Restart `kb(workbench.action.debug.restart)`           | Terminate the current program execution and start debugging again using the current run configuration                                                             |
| Stop `kb(workbench.action.debug.stop)`                 | Terminate the current program execution                                                                                                                            |

**Review by gregvanl — APPROVED** [review]
Thanks!
Sorry for the delay, we were working up to the latest release.

**Pull request merged**
