### PR TITLE
Fix highlight lang names

### PR DESCRIPTION
**Pull request by rzhao271**
Fixes the syntax names used for highlighting so that shiki can highlight the blocks properly.

### CODE REVIEW

**Comment by gregvanl** [comment]
For command line examples, should we be using `sh` or `bash`? 
In vscode-docs right now we have over 200 instances of ```bash and only 10 of ```sh

**Comment by rzhao271** [comment]
I'm thinking it can just be `sh` in this case considering there's no bash-isms in the code blocks.

**Comment by gregvanl** [comment]
Is there any rendering difference between sh or bash?
I could try experimenting locally to see what changes if we update the use of bash to sh

**Comment by rzhao271** [comment]
Looking at shiki 0.10 docs and the latest shiki docs, sh and bash should produce the same result.
Ref https://github.com/shikijs/shiki/blob/d21acb5fd408c69b750b5d6f41a62eac03f607d2/docs/languages.md

**Review by gregvanl — APPROVED** [review]

**Pull request merged**
