### PR TITLE
Updates Mac menu path for Settings

### PR DESCRIPTION
**Pull request by shawnthompson**
Preferences is now titled Settings...

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @shawnthompson Thanks for pointing this out. What version of macOS are you using?
I'm on Monterey and I still see Code > Preferences.
I wonder if this change started with the Ventura update?

**Comment by shawnthompson** [comment]
Hi @gregvanl, 

I am using Ventura 13.1 so it much be something that changed in this version of macOS.

Now that I think of it, I heard that Apple changed **preferences** to **settings** to make is more similar to wording in iOS.

Would this mean you'd probably have to a note in your documentation for the different versions of macOS?

**Comment by gregvanl** [comment]
Yep, there are about 35 instances in the docs where we call out **Code** > **Preferences**.
I'm reluctant to make the changes quite yet, given that the majority of Mac users won't be on Ventura for some time and it will get unwieldy to put both menu paths.
We could do something like **Code** > **Preferences/Settings** but that may be confusing

**Comment by gregvanl** [comment]
Closing this PR as we've implemented platform and version detection on code.visualstudio.com so that **File** > **Preferences** is rendered appropriately for readers on macOS, including those on version Ventura (13) and above.

Window/Linux: **File** > **Preferences** > blah
macOS: **Code** > **Preferences** > blah
macOS (13+): **Code** > **Settings** > blah

**Pull request closed without merging**
