### PR TITLE
Add Ballerina Language

### PR DESCRIPTION
**Pull request by gigara**
Add Ballerina language support.

### CODE REVIEW

**Comment by gigara** [comment]
@microsoft-github-policy-service agree

**Comment by gregvanl** [comment]
Hi @gigara Thank you for your interest in the VS Code documentation and taking the time to create a PR.
Closing this PR for now as code.visualstudio.com is likely not the best place to host this content. It looks like there is already very good documentation about the VS Code Ballerina extension at https://ballerina.io/learn/vs-code-extension and should reach a larger audience of Ballerina users.
Even though the PR is closed, users can still find this introduction via search or via the direct GitHub URL https://github.com/microsoft/vscode-docs/blob/dc1e8994913ce83523d767d9e5ae7e5d7dcf4288/docs/languages/ballerina.md

**Comment by gigara** [comment]
@gregvanl We will remove the above webpage and move the content to vscode-docs since most languages host the docs there.

**Comment by gregvanl** [comment]
Hi @gigara We only host a sub-set of all available programming languages on code.visualstudio.com in order to keep our doc set manageable. We do not think a Ballerina language article will have a sufficient sized audience at this time to justify the cost.
I recommend that you keep your documentation on the Ballerina tech site https://ballerina.io as it is easier for your users to find and your engineers contribute

**Pull request closed without merging**
