### PR TITLE
Update supported Java versions

### PR DESCRIPTION
**Pull request by 0dinD**
For reference, see:
- redhat-developer/vscode-java#3728
- eclipse-jdtls/eclipse.jdt.ls#3266

### CODE REVIEW

**Comment by ntrogh** [comment]
@0dinD thanks for updating our docs. 

@nickzhums can you review these changes?

**Comment by nickzhums** [comment]
@jdneo @testforstephen Could you please help take a look at the proposed changes? I think we do support JDK 1.5 or above, so need you guys to double check

**Comment by jdneo** [comment]
@nickzhums, start from 1.33.0 the minimum supported jdk version changes to 1.8

https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3227

**Review by jdneo — APPROVED** [review]

**Review by testforstephen — APPROVED** [review]
LGTM. @0dinD thanks for contribution.

**Review by nickzhums — APPROVED** [review]

**Review by ntrogh — APPROVED** [review]

**Pull request merged**
