### PR TITLE
It now defaults to PowerShell even on Win7

### PR DESCRIPTION
**Pull request by fireattack**
Tested on 1.53.1

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @fireattack Thank you for submitting at PR and your interest in the VS Code documentation.
I'm not sure your change is correct and when I look at the VS Code source code, I still see a check for Windows 10.
Might you have terminal.integrated.shell.windows set in your settings.json?

**Comment by fireattack** [comment]
> Hi @fireattack Thank you for submitting at PR and your interest in the VS Code documentation.
> I'm not sure your change is correct and when I look at the VS Code source code, I still see a check for Windows 10.
> Might you have terminal.integrated.shell.windows set in your settings.json?

Nope, I noticed my terminal suddenly became Powershell on after updated to 1.53.1. I then created a brand new profile with portable VS Code and can confirm it by default uses PS now (with no `terminal.integrated.shell.windows` set up).

Please see the screenshot below:

image

**Comment by gregvanl** [comment]
@fireattack Thanks for confirming. I've reached out to a VS Code engineer and will reply back here on whether its a "feature" or a bug. :-)

**Comment by gregvanl** [comment]
You are absolutely correct. Thanks for pointing this out!

**Pull request merged**
