### PR TITLE
Python tutorial: update screenshots

### LINKED ISSUE #3174: Update screenshots in the Getting Started with Python in VS Code tutorial
https://code.visualstudio.com/docs/python/python-tutorial

Screenshots still have the old VS Code icons

### PR DESCRIPTION
**Pull request by emtei**
Resolves #3174

### CODE REVIEW

**Comment by gregvanl** [comment]
@luabud Have a look at this community PR to resolve your issue.

**Comment by JoshuaPartlow** [comment]
Hi @emtei - Thanks very much for your contribution. It looks good, but we actually have another open PR in progress that updates the screen shots (https://github.com/microsoft/vscode-docs/pull/3181), as well as other parts of the tutorial. If you have some time, we'd certainly welcome any feedback you have on the updated tutorial topic and hope that you'll continue to make contributions to the docs. Thanks again.

**Comment by emtei** [comment]
That's fine. I'm sorry but I didn't notice your PR before because it wasn't linked to the issue #3174.

**Comment by JoshuaPartlow** [comment]
My apologies for not having the PR linked in the issue. It actually touches a few open issues, I'll get I added to them now.

**Pull request closed without merging**
