### PR TITLE
update livestream

### PR DESCRIPTION
**Pull request by burkeholland**
Update to events-data.json

### CODE REVIEW

**Comment by gregvanl** [comment]
@burkeholland There is a typo ("Sart and Stop") in the description (same text is in events-data.json, email invite, YouTube page).
The description could use some tuning. How about:
"The AKS extension for VS Code reduces the heavy lifting and enhances the DevOps experience for developers working with Azure resources. You can manage AKS Clusters without leaving VS Code, quickly create and navigate to clusters on the Azure Portal, and the integrated GitHub workflow makes deployment easy."

**Comment by PGray348** [comment]
I've updated the description in ADO and on YouTube and meet up.

**Comment by burkeholland** [comment]
#sign-off

**Comment by gregvanl** [comment]
I'll go ahead and merge this PR and update the events-data.json text.

**Comment by burkeholland** [comment]
Thanks, Greg! I think I had 2 branches named similar things there and I updated the wrong one.

**Pull request merged**
