### PR TITLE
Fix and update the doc for java-webapp to the latest

### PR DESCRIPTION
**Pull request by silenceJialuo**
This is Jialuo Gan here and I am the PM at Microsoft for Java on Azure Tooling. I have fixed all the issues to keep it up to date. Please wait for Java 17 runtime issues to be fixed and then merge this doc to the main. I will update it later.

### CODE REVIEW

**Review by Gesisfm — APPROVED** [review]

**Review by Gesisfm — APPROVED** [review]
Duplicate of #

**Review by Gesisfm — APPROVED** [review]

**Review by Gesisfm — APPROVED** [review]
重複# #6005

**Comment by gregvanl** [comment]
Hi @silenceJialuo I noticed that the two `devicelogin` .png images are also used in /docs/java/java-spring-apps.md and that tutorials also has the same login section as java-webapp.md. 
Should java-spring-apps.md be updated the same way?

**Comment by silenceJialuo** [comment]
Hi @gregvanl , thanks for your kind remainder. There are some differences in java-spring-apps.md compared with java-spring-apps.md. For Azure Spring Apps extension, we provide another explorer for users to sign in. I also update the login in sections in the file of  java-spring-apps.md. And it's ready to merge.

**Review by gregvanl — APPROVED** [review]
Thanks!

**Pull request merged**
