### PR TITLE
Replace "python" with "pythonArgs" in launch.json

### PR DESCRIPTION
**Pull request by ianfiske**
Removed "python" because it is no longer supported.  Added "pythonArgs" from https://github.com/microsoft/vscode-python/issues/13218.

### CODE REVIEW

**Comment by JoshuaPartlow** [comment]
Hi @ianfiske - Thank you for submitting a PR for the VS Code Python docs. We'll review it soon and get back to you if there are any questions.

**Comment by int19h** [comment]
This isn't quite right - "python" was not removed or deprecated. What we deprecated (but not removed) is the array-syntax for "python" that allows passing interpreter path + arguments in a single property. So now "python" is meant to be just the interpreter, and "pythonArgs" is for arguments to it.

**Comment by JoshuaPartlow** [comment]
Hi @ianfiske - Are you able to address @int19h feedback in your PR? If not, I can open an issue on the docs and address soon.

**Comment by ianfiske** [comment]
@JoshuaPartlow thanks for following up -- apologies, but I'm busy with other things and don't have time to get this correct right now.  Please do take care of this and feel free to close this PR.

**Comment by JoshuaPartlow** [comment]
Sounds good @ianfiske. Tracking with issue https://github.com/microsoft/vscode-docs/issues/4161

**Pull request closed without merging**
