### PR TITLE
Add auto save delay default of 1000 ms

### PR DESCRIPTION
**Pull request by joshunger**
Add auto save delay default of 0 ms

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @joshunger Thank you for your PR but I'm confused. The `files.autoSaveDelay` is 1000 ms by default, not 0 ms.

**Comment by joshunger** [comment]
Good catch! I'll take a look I thought it was 0 when I read the code.

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/files.contribution.ts

**Comment by joshunger** [comment]
Thanks I'll find what I was looking at and fix.

**Comment by joshunger** [comment]
@gregvanl I was updating the merge request what's up with closing it?

**Comment by gregvanl** [comment]
Oops, I figured you'd create a new PR. Feel free to reuse this one if you like but please update the title for the commit history.

**Comment by joshunger** [comment]
No problem I can do either!

**Comment by joshunger** [comment]
Closed in favor of https://github.com/Microsoft/vscode-docs/pull/1352/

**Pull request closed without merging**
