### PR TITLE
Update ssh.md

### PR DESCRIPTION
**Pull request by tyrionlannistar**
The suggested way "sc config ssh-agent start=auto" does not work.
Error: Set-Content : A positional parameter cannot be found that accepts argument 'startup'.

### CODE REVIEW

**Comment by roblourens** [comment]
I think this is the command for cmd.exe, not powershell. I would rather describe a command to run than some buttons to click in a gui. I think it would be better to have documentation for powershell, would that have been more clear?

**Comment by roblourens** [comment]
I realized this is the containers topic so I'll leave it up to @chrmarti or whoever wrote this, but this is the powershell script we show for SSH 
https://github.com/microsoft/vscode-docs/blob/main/docs/remote/troubleshooting.md#setting-up-the-ssh-agent

**Comment by gregvanl** [comment]
Giving a mention to @karolz-ms, who most recently worked on the topic.

**Comment by karolz-ms** [comment]
I like how the remote docs use PS built-in cmdlets to make the service start automatically, we should do the same in containers docs. Thanks @roblourens for the tip!

**Comment by tyrionlannistar** [comment]
@roblourens  It would be great to add the remark, that it is a cmd and not a powershell command. There are many discussions out there, on how to start the service. I was not aware, that cmd and powershell commands differ. :)

**Comment by gregvanl** [comment]
Closing this PR. Assuming @karolz-ms will work on a new PR with input from @tyrionlannistar.
Thanks @tyrionlannistar for pointing out the possible confusion.

**Comment by karolz-ms** [comment]
Hmm, I was not really volunteering to do a new PR ☺️ @ghogen could I use your help here?

If not, no worries, just LMK, I can squeeze this in sometime next week

**Comment by gregvanl** [comment]
@karolz-ms No worries, looks like there is enough context here and in https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent for @ghogen to put something together.

**Pull request closed without merging**
