### PR TITLE
Azure Account -> Azure Resources and GitLab support removal, GitHub addition

### PR DESCRIPTION
**Pull request by bwateratmsft**
A couple of things in this PR.

- Azure Account is being slowly deprecated and replaced with the built-in Microsoft authentication provider. I could use some help with the verbiage here. The Azure Resources extension is required to sign in to some tenants (e.g., those with extra MFA after the primary sign-in) and is recommended (though not strictly required) if a sovereign cloud is being used.
- GitLab container registry support has been removed from the Docker extension (see https://github.com/microsoft/vscode-docker/issues/4132)
- GitHub container registry support has been added to the Docker extension (see https://github.com/microsoft/vscode-docker/issues/869)

Closes https://github.com/microsoft/vscode-docker/issues/4147

### CODE REVIEW

**Comment by fiveisprime** [comment]
The changes look good. The Python and Java articles are pretty intense - it's not something to change in this PR, but I wonder how helpful those are.

> Alex, we may want to add some specific documentation somewhere on the docs site about the Azure Resources extension, with particular focus on sign in (sovereign clouds, MFA-requiring tenants, etc.)

I like how the Docker section has an overview. Maybe the Azure section could use an overview rather than the "extensions" page that goes over the Azure Resources extension. That "extensions" landing page was built when it was more difficult to discover the various service extensions, which isn't so much an issue now that every service shows up by default.

**Comment by ghogen** [comment]
@bwateratmsft  
Thanks, this looks great, I just have one question about that first image that shows your GitHub id. I don't know the VS Code policies as well, but on the Learn platform, we have a PII policy that would ask us to adjust the image in some way to not show any PII.

**Comment by bwateratmsft** [comment]
> @bwateratmsft Thanks, this looks great, I just have one question about that first image that shows your GitHub id. I don't know the VS Code policies as well, but on the Learn platform, we have a PII policy that would ask us to adjust the image in some way to not show any identifiable information.

I'll take a new screenshot without. But the old GitLab image had a GitLab username in it so I didn't think it'd matter.

**Review by ghogen — APPROVED** [review]

**Comment by gregvanl** [comment]
published

**Pull request merged**
