### PR TITLE
Add notifications colors to Theme Color Reference

### PR DESCRIPTION
**Pull request by akamud**
Add documentation to new features added in https://github.com/Microsoft/vscode/pull/28471

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @akamud, since the feature is not yet in the stable build, we shouldn't merge this doc change into master yet. There are two options: sit on the PR until the next stable release or move this PR to the vscode-docs vnext branch. The vnext branch is where we do prerelease documentation and the commits are merged to vscode-docs master at the time of the release.

**Comment by akamud** [comment]
I'll rebase this on `vnext` then. Thanks!

**Comment by gregvanl** [comment]
Great, Thanks

**Comment by akamud** [comment]
Done!

**Comment by gregvanl** [comment]
Thanks!

**Pull request merged**
