### PR TITLE
Add selectedText to variable substitution section

### PR DESCRIPTION
**Pull request by yitongding**
Add doc for Microsoft/vscode#39483

### CODE REVIEW

**Comment by isidorn** [comment]
This looks good to me.
Assigning to @gregvanl for the final review

**Comment by gregvanl** [comment]
@yitongding Can you move this PR to our vscode-docs vnext branch since it documents a change that will be coming in the next release? It will then go to vscode-docs master along with the rest of the 1.20 documentation updates. Thanks.

**Comment by yitongding** [comment]
@gregvanl Thanks for reminding. Just did.

**Comment by gregvanl** [comment]
@yitongding Great, thanks.

**Pull request merged**
