### PR TITLE
point to lazy loading NVM article for those with NVM issue

### PR DESCRIPTION
**Pull request by jasonwilliams**
After having an issue with the terminal failing to load I found a useful blog post which talks about the same thing and how to resolve it via lazy loading. I think it's worth adding to the FAQ's so others can be assisted from this too.

Fixes: https://github.com/microsoft/vscode/issues/148434

### CODE REVIEW

**Comment by Tyriar** [comment]
Would prefer not to recommend/endorse a plugin that we don't know anything about and doesn't seem to be often updated. There's already a suggestion to avoid using nvm which I think is sufficient.

**Comment by jasonwilliams** [comment]
Hey @ljharb just CCing you to let you know nvm doesn't seem to play nice with VSCode. The only option seems to be using the lazy load plugin, but that doesn't seem to be an accepted solution here. I'm not sure if you're (or anyone from nvm) are aware or plan to put in place any performance/lazy loading mechanisms in future. 

Original issue: https://github.com/microsoft/vscode/issues/148434
Issue also referenced here: https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails

**Comment by ljharb** [comment]
@Tyriar why would nvm be avoided with vscode?? I use them together exclusively and they work perfectly fine.

@jasonwilliams thanks for the heads up. I’m not sure when that advice was written, but about a year ago i shipped a large performance update, and the problems should be largely eliminated.

If there’s still a problem, filing an issue would be much more appropriate than recommending users avoid the most used node package manager (and than recommending a much more obscure one).

**Comment by jasonwilliams** [comment]
> Would prefer not to recommend/endorse a plugin that we don't know anything about and doesn't seem to be often updated. There's already a suggestion to avoid using nvm which I think is sufficient.

It’s inconsistent with the WSL docs which say to install nvm https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl you may want to update those also if that’s the message you want to send.

**Comment by ljharb** [comment]
fwiw the WSL docs here are flawless - kudos to that team for being one of the few instances of "how to install node with nvm" instructions i've ever seen on the internet that's actually _accurate_!

**Pull request closed without merging**
