### PR TITLE
Update hello world example to use react v18 api

### LINKED ISSUE #6586: Documentation Tutorial 'Using React in Visual Studio Code' Needs Updated to latest React v18
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1 (user setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Follow the steps for https://code.visualstudio.com/docs/nodejs/reactjs-tutorial
2. The Hello World section uses code that is no longer supported (ex: ReactDOM.render) as of React version 18; see https://github.com/reactwg/react-18/discussions/5

### PR DESCRIPTION
**Pull request by alexwkleung**
Resolves #6586.

The Hello World example is updated to use the React v18 API. I tried this with Create React App v5.0.1 which uses React v18.2.0, and it works as intended.

Let me know if I need to make any changes.

### CODE REVIEW

**Comment by alexwkleung** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by gregvanl** [comment]
Hi @alexwkleung Thank you for working on this PR.
We should also update the screenshots in the tutorial since they display the obsolete generated code

**Comment by alexwkleung** [comment]
> Hi @alexwkleung Thank you for working on this PR. We should also update the screenshots in the tutorial since they display the obsolete generated code

Done. 

All screenshots are updated except the browser ones (my host is macOS, wasn't sure if it was allowed).

I also deleted `debug-config.png` and `eslintrc-intellisense.png` since they weren't used in the tutorial.

**Review by gregvanl — APPROVED** [review]
Thanks! Nice job

**Pull request merged**
