### PR TITLE
Adds cmder specific details for integrated terminal

### PR DESCRIPTION
**Pull request by johnkors**
See https://github.com/Microsoft/vscode/issues/12006

### CODE REVIEW

**Comment by Tyriar** [comment]
@gregvanl the instructions for setting `cmd.exe` are going to be more complicated when 64-bit VS Code on Windows  is in stable. `C:\\WINDOWS\\Sysnative\\cmd.exe` is correct only on *32-bit processes* on *64-bit Windows*, everything else (32 on 32, 64 on 64) should use `C\\WINDOWS\\System32\\cmd.exe`.

Any ideas how to concisely indicate this here?

Also the Cmder section should probably go in common questions.

**Comment by gregvanl** [comment]
@Tyriar We can explicitly call out and show an example for the most common case (64 on 64?). Users on other configurations should be able to adjust based on the example.

**Comment by Tyriar** [comment]
@gregvanl well the most common case right now and likely for the next few months until people jump over to the 64-bit client is 32 on 64.

**Comment by gregvanl** [comment]
Thanks! I move the tip to Common Questions. https://github.com/Microsoft/vscode-docs/commit/c4df2a2e57f320387a5ef396859da39433e85a36

**Comment by johnkors** [comment]
:+1:

**Pull request merged**
