### PR TITLE
Update the Quick Open keybinding for Win

### PR DESCRIPTION
**Pull request by justinwhite15**
Update from ctrl+p to ctrl+shift+p

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @justinwhite15, Ctrl+Shift+P opens the Command Palette on Windows.  Ctrl+P brings up Quick Open.
Also you are modifying one of our website keyboard shortcut mapping files under the scripts directory. What are you trying to do?

**Comment by justinwhite15** [comment]
Ahhh...got it.  I think what I should be instead requesting/suggesting is that on the page:
https://code.visualstudio.com/docs/editor/versioncontrol#_branches-and-tags

That is should say you should use the Command Palette to run Git Branch which is Ctrl+Shift+P.  Does that make sense?

**Comment by gregvanl** [comment]
That section is in flux as the new Git extension doesn't yet support the Git branch and checkout commands in Quick Open. If you switch back to the old version (bring up Command Palette, then run SCM: Disable Preview SCM), you'll see "git" in the Quick Open list.
Let me check with the developer working on this and see if git in Quick Open is coming back next release or if we need to update the documentation.
Thanks for catching this.

**Comment by gregvanl** [comment]
Doesn't look like it is coming soon. https://github.com/Microsoft/vscode/issues/24408.

**Pull request closed without merging**
