### PR TITLE
Top 10 doc pages social images

### PR DESCRIPTION
**Pull request by bgashler1**
Social sharing images optimized to work on all major social platforms
https://github.com/Microsoft/vscode-website/issues/474

FYI @gregvanl

### CODE REVIEW

**Comment by gregvanl** [comment]
@bgashler1 Why are the first two images for keybinding and debugging different?

**Comment by bgashler1** [comment]
We could talk about this but essentially my rationale for doing this was because social media like Twitter and Facebook often have a title/description adjacent to whatever image is being posted.  So I wanted the visual to be interesting and visually drawing.  A plain title just seemed kind of plain and less eye-catching.

**Comment by gregvanl** [comment]
Not sure we are talking about the same thing. I liked the language images which have a title (VS Code + C#) and then clear screenshot below. I don't care for the keybinding, codebasics, and debugging images which have a faded screenshot in the background and centered text.

**Comment by gregvanl** [comment]
@bgashler1 Where are we on this pull request? Were you going to change the first few images based on feedback. I think we talked about putting text on top and clear image with fade down the page - similar to other language page images?

**Comment by bgashler1** [comment]
@gregvanl these images were all completed a while ago.  I'll add them into this PR and assign you when ready.  Thanks for pinging me on this.

**Comment by bgashler1** [comment]
@gregvanl just added those images for you.

**Pull request merged**
