### PR TITLE
Update docs now that the Docker extension is a workspace extension by default

### PR DESCRIPTION
**Pull request by Chuxel**
Partial resolution to https://github.com/microsoft/vscode-remote-release/issues/1826

### CODE REVIEW

**Comment by karolz-ms** [comment]
@Chuxel @gregvanl thank you for taking care to update the docs to reflect the current Docker extension behavior.

Question though: in case if someone is working with a remote machine that has its own Docker daemon, but wants to see/manipulate Docker assets controlled by their local Docker daemon, to me by far the best option is the one that you list first in the docs, namely, to open a different VS Code window that uses local workspace/context. 

I see no advantage to forcing the extension to be loaded as "UI" extension, or going through the hoops of setting up a development container just to see local Docker assets. So why are we even describing these, arguably inferior, options in the docs?

Am I missing something?

**Comment by Chuxel** [comment]
@karolz-ms That pre-supposes that working with local containers is the exception flow.  If it's primary, switching to UI makes more sense -- particularly if you prefer not to have multiple active VS Code windows open. That's why it was UI by default originally.

**Comment by karolz-ms** [comment]
OK, I guess I am just so used to having multiple VS Code windows open that I haven't even imagined someone might not like it. Thanks for clarification!

**Comment by Chuxel** [comment]
@karolz-ms Oh, and one other thing, on adding the Docker CLI into the container, that's actually the Docker-in-Docker and Kubernetes - Helm scenarios.  It happens when you are using a container as a development sandbox and deploying to other containers - even if just to test your non-dev config.   

The links there point to the dev containers in the other repo that we just updated. :)

**Pull request merged**
