### PR TITLE
Adding Editor in front of Sticky Scroll in the release notes

### PR DESCRIPTION
**Pull request by aiday-mar**

### CODE REVIEW

**Comment by isidorn** [comment]
@aiday-mar I think you should not have merged it. The mistake is that you merged again `main`. You should have merged against `vnext`. We can revert?

fyi @gregvanl @alexdima

**Comment by aiday-mar** [comment]
Ah yes, my mistake, I remembered the vnext. I followed the following tutorial to revert the merge https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request.

**Comment by isidorn** [comment]
Thanks for reverting. Just make sure to apply your changes to vnext. And before merging double check the number of changes in the PR, if the number of changes is huge that is a good indicator something is off :)

**Comment by gregvanl** [comment]
@isidorn Thanks for catching this! Everything looks back to normal in vscode-docs main.

**Comment by aiday-mar** [comment]
Right thanks for the tip!

**Pull request merged**
