### PR TITLE
Code Lens Roundup

### PR DESCRIPTION
**Pull request by waderyan**
@gregvanl I'm just about there with this. Care to have a look? Probably won't publish until Monday of next week. 

cc @egamma @seanmcbreen

### CODE REVIEW

**Comment by gregvanl** [comment]
@waderyan Probably won't get to this until next week. We also have the Go and TSQL topics going out and should space all these out for Twitter attention.

**Comment by egamma** [comment]
@waderyan looks good to me. Since you show the Kiss complexity code lens. This extension has tons of customization options and @jrieken customized it so that you get a different emoji depending on the complexity of the code. You could show a screenshot from this setup and tell, this is how we use it ourselves :smile:

**Comment by jrieken** [comment]
Yeah, me config is this:

```json
    "codemetrics.basics.ComplexityLevelExtremeDescription": "😱",
    "codemetrics.basics.ComplexityLevelHighDescription": "😳",
    "codemetrics.basics.ComplexityLevelLowDescription": "🤓",
    "codemetrics.basics.ComplexityLevelNormalDescription": "🤔",
    "codemetrics.basics.ComplexityTemplate": "Complexity is {0} {1}",
```

**Comment by waderyan** [comment]
Done and Done!

@gregvanl agreed. Let's wait until next Monday or Tuesday.

**Pull request merged**
