### PR TITLE
trigger key for menu item's 'alt' command is Shift on Windows and Linux

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
See https://github.com/microsoft/vscode/commit/0cd3c4c9946f56ddecd580817c3e1c07fe7f0ba4

cc @isidorn

### CODE REVIEW

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for this update. However on Win and Linux we will trigger the alternative command both if `Alt` or `Shift` are pressed. Can we make this more clear in the description?

**Comment by gjsjohnmurray** [comment]
@isidorn thanks for the feedback. I have pushed a change for you to review.

**Comment by isidorn** [comment]
@gjsjohnmurray  Looks good! I only now noticed, but we always do changes in our docs against the `vnext` branch so @gregvanl has a chance to review everything before merging to master.
So can you please change this PR that it merges into `vnext` branch? Thanks!

**Comment by gjsjohnmurray** [comment]
@isidorn I hope I did that right. First time I've had to attempt it.

**Comment by gjsjohnmurray** [comment]
@gregvanl you have previously taken doc changes from me direct into master. Maybe the process is different if @isidorn wants to approve and merge this into `vnext` so you get to review it later.

**Comment by gjsjohnmurray** [comment]
In this case the change referred to released in 1.53 so the doc update doesn't need to wait for the next release. But I don't mind if it does anyway.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks. However you did not do it correctly - if I look at the changes there are much more.

What I suggest is the following:
1. Locally checkout vnext branch
2. On top of it create your branch with your changes
3. From your branch create a PR and choose to merge against vnext

THen we should be good.
Sorry for complicating. Maybe merging into master is ok, I was not aware of that.

**Comment by gjsjohnmurray** [comment]
OK, I will submit a new PR against vnext shortly.

**Comment by gregvanl** [comment]
@gjsjohnmurray It's fine to submit PRs for vscode-docs master and I do a review before anything goes live on code.visualstudio.com. We use vnext for content related to the next release, in this case, 1.54.
I'll cherry pick your change to vscode-docs master. Sorry for the confusion.

**Comment by isidorn** [comment]
@gregvanl thanks for clarifying. I was the cause of confusion :)

**Comment by gregvanl** [comment]
No worries, and appreciate the extra caution ;-)

**Pull request closed without merging**
