### PR TITLE
Add bandit to python linting docs

### PR DESCRIPTION
**Pull request by demus**
per https://github.com/Microsoft/vscode-python/pull/2775

@DonJayamanne

### CODE REVIEW

**Comment by kraigb** [comment]
Thanks @demus. Can you confirm if this made it into the 2018.09 release that was put out last week? I want to make sure before adding it to the docs; if it missed that release, we'll need to wait on this until the end of the month.

**Comment by demus** [comment]
@kraigb I don't think it made it in to that release unfortunately

**Comment by kraigb** [comment]
No problem; I'll just put this PR on hold and set it on the backlog for now. I'll cycle back with it after the next release.

**Comment by brettcannon** [comment]
The release is out so this can be merged!

**Comment by kraigb** [comment]
Closes #2136

**Comment by kraigb** [comment]
Thanks again, @demus!

**Pull request merged**
