### PR TITLE
Update debugging.md

### PR DESCRIPTION
**Pull request by halilural**

### CODE REVIEW

**Comment by halilural** [comment]
added 8

**Comment by gregvanl** [comment]
Hi @halilural Why would you like to change the debugging topic Order metadata? The Order number determines the placement in the TOC and the versioncontrol topic is already number 8.

**Comment by halilural** [comment]
@gregvanl sorry, I realised that after I opened pull request.

**Comment by gregvanl** [comment]
@halilural OK, if I close this?

**Pull request closed without merging**
