### PR TITLE
Add documentation for projectName on compose tasks

### PR DESCRIPTION
**Pull request by Xitric**
This PR updates the documentation to include a new property that will be introduced to Docker compose task definitions via microsoft/vscode-docker#3440.

**This is not ready to be merged yet**. I will update this PR once it is known when the new property is released.

### CODE REVIEW

**Comment by bwateratmsft** [comment]
Looks good to me! @gregvanl please hold until our 1.21 release, tentatively 21 Mar. Thanks!

**Comment by bwateratmsft** [comment]
@ucheNkadiCode FYI

**Comment by ucheNkadiCode** [comment]
Thanks @Xitric!

**Comment by bwateratmsft** [comment]
@gregvanl we just released Docker extension 1.21.0, so this can now be merged. Thanks!

**Pull request merged**
