### PR TITLE
Updated Python Environment Docs with Updated Images

### LINKED ISSUE #5130: Update screenshots related to interpreter quickpicker in vscode docs
Couple of screenshots and their description in https://code.visualstudio.com/docs/python/environments needs updating:

cc @luabud

### PR DESCRIPTION
**Pull request by Dhananjay-JSR**
This PR Closes #5130

# CHANGE ONE

# CHANGE TWO

### CODE REVIEW

**Comment by luabud** [comment]
Hi @Dhananjay-JSR! Thank you so much for being willing to contribute 😊 
There is actually another update coming up this week that would make the screenshots different (it's available on our [insiders build](https://code.visualstudio.com/docs/languages/python#_insiders-program)). Would you be open to updating your PR with the following images below?

# Change One
image

# Change Two
image

**Comment by Dhananjay-JSR** [comment]
@luabud I have updated my PR , Please take a look for any other changes required 😃

**Comment by gregvanl** [comment]
@luabud Does this need to wait until later in the week to merge after the extension release?

**Comment by luabud** [comment]
@gregvanl yes please! 😊 we'll release right after VS Code releases.

**Comment by gregvanl** [comment]
Added `don't merge` label until the extension update goes out

**Pull request merged**
