### PR TITLE
Fixed a typo.

### PR DESCRIPTION
**Pull request by phistuck**

### CODE REVIEW

**Comment by gregvanl** [comment]
Thanks!

**Comment by phistuck** [comment]
@gregvanl - by the way, the syntax of the patterns is not mentioned anywhere. I would have submitted a pull request to clarify this, but I really do not know what it is.

**Comment by gregvanl** [comment]
@phistuck I think they are standard glob patterns but I'll confirm.

**Comment by gregvanl** [comment]
@phistuck Yes, include and exclude use glob patterns https://en.wikipedia.org/wiki/Glob_(programming). jsconfig.json is based on tsconfig.json https://www.typescriptlang.org/docs/handbook/tsconfig-json.html and you can see the description of include and exclude.

**Pull request merged**
