### PR TITLE
Update Remote - Containers command name to "Clone Repository in Container Volume"

### LINKED ISSUE #3948: Rename 'Open Repository in Container' to 'Clone Repository in Container Volume'
For 1.49 'Open Repository in Container' was changed to 'Clone Repository in Container Volume'.

### PR DESCRIPTION
**Pull request by bamurtaugh**
Please let me know if it looks like I might have missed any instances of updating "Open Repository in Container" to "Clone Repository in Container Volume." Also, I didn't see any screenshots that included the command, so I only made updates to text, but happy to update any images I might have missed.

As we discussed in the issue, proposing the merge for branch vnext.

Fixes #3948

### CODE REVIEW

**Comment by gregvanl** [comment]
@bamurtaugh I've merged master to vnext, can you refresh this PR so it only has your updates? Thanks

**Comment by bamurtaugh** [comment]
@gregvanl Thanks for merging those changes and letting me know! I believe I refreshed so that now just my changes are showing in this PR.

**Comment by gregvanl** [comment]
@bamurtaugh Do you also want to update your 7/27 blog post? It mentions Open Repository in Container and has a couple of outdated screenshots.
There are also some mentions of Open Repository in Container in the release notes but I'm less worried about those since they are accurate for the specific release and we'll no doubt mention the rename in the next release notes.
While the blog post is a point in time article, it may still be referenced as it is really a tutorial.

**Comment by bamurtaugh** [comment]
@gregvanl That's a good point- especially since that blog post is considered more of a tutorial/guide rather than just a point in time for a specific release. I'll work on making some updates and open up a PR with the changes.

**Comment by bamurtaugh** [comment]
Opened #3976 to update wording and a couple screenshots.

**Pull request merged**
