### PR TITLE
Document problem matcher file location "autodetect" configuration 

### LINKED ISSUE #3182: Autodetect is not mentioned in tasks.json docs
https://code.visualstudio.com/docs/editor/tasks-appendix is not mentioning `autoDetect` for tasks.json

See https://github.com/microsoft/vscode/issues/74824

### PR DESCRIPTION
**Pull request by joanrieu**
Fixes #3182 using documentation from microsoft/vscode#83803

### CODE REVIEW

**Comment by gregvanl** [comment]
@alexr00 I'm assigned you this PR along with the issue as you currently have the vscode repo issue.

**Comment by yellowfish7** [comment]
So what’s the issue?

**Comment by yellowfish7** [comment]
I don’t want to be guide , someone else would better I think

**Comment by yellowfish7** [comment]
Phone backed up and ready to be reset , you call gents

**Comment by yellowfish7** [comment]
Pull request?

**Comment by yellowfish7** [comment]
Get it off an I’ll pull it

**Comment by yellowfish7** [comment]
Listen I read theory, of want me to help , incentive would be good but goal of project doesn’t seem like the vs code objectives, seems other code was written by other independently

**Pull request merged**
