### PR TITLE
Update nodejs-debugging.md

### PR DESCRIPTION
**Pull request by dominicwhyte**
Reflects deprecated --debug flag and using the inspector protocol on default port 9229

### CODE REVIEW

**Comment by roblourens** [comment]
Thanks for pointing this out, but could you change the other usages in this doc too? I think all the places that reference `--debug` and `"port": 5858` on this page should be changed. Also, you shouldn't need to set `"protocol": "inspector"` for the attach config - it should be autodetected.

cc @weinand

**Comment by gregvanl** [comment]
Thanks. I'll change the other --debug references as well.

**Comment by gregvanl** [comment]
Finished update with https://github.com/Microsoft/vscode-docs/commit/54d3d82b98a3401fafa25aeefe6b1d0742f8fe9e

**Comment by roblourens** [comment]
Also updated the node-debug defaults in package.json

**Pull request merged**
