### PR TITLE
Update RPM installation command for code.rpm

### PR DESCRIPTION
**Pull request by bikundkumar**
This pull request updates the documentation to include a manual installation command for the VS Code `.rpm` package using `dnf`:

`sudo dnf install ./code-<arch>.rpm`

- **Purpose:** Simplifies the process for users who prefer to manually download and install the `.rpm` package without adding the Microsoft repository.
- **Benefit:** Allows users to install locally downloaded packages while ensuring dependencies are handled by `dnf`. It also provides clear instructions for using the local path (`./`) for easy navigation.

### CODE REVIEW

**Comment by ntrogh** [comment]
@bikundkumar the doc already has the instructions for installing from a downloaded package. The PR only renames the placeholder for the file with another placeholder.

**Comment by bikundkumar** [comment]
Hi @ntrogh ,

Thank you for the feedback! I noticed that the documentation does indeed include instructions for installing from a downloaded package, but my aim with this pull request was to:

1. Simplify the placeholder name to clearly indicate the local path for easier navigation (i.e., `./code-<arch>.rpm`).
2. Emphasize the use of `dnf` to ensure dependencies are resolved during the installation process, as this might not always be clear to users unfamiliar with package management via `dnf`.

I believe this small update will make the instructions clearer and more user-friendly for those manually installing the `.rpm` package. I’d love to hear your thoughts on this.

**Comment by ntrogh** [comment]
@bikundkumar thanks for clarifying. We prefer to keep the placeholder generic, as we have no indication of where the user downloads the file, and if there are changes to the actual file name. Also, it aligns with other occurrences of `<file>` in the docs.

**Comment by bikundkumar** [comment]
@ntrogh Thank you for the clarification! I understand the importance of maintaining consistency across the documentation. I’ll keep this in mind for future contributions.

If there’s anything else I can help with or suggestions for areas to focus on, I’d love to continue contributing to the project!

**Comment by ntrogh** [comment]
@bikundkumar appreciate it. You can check out open issues or raise an issue/create a PR whenever you notice something in our documentation!

**Pull request closed without merging**
