### PR TITLE
Document inno setup arguments

### PR DESCRIPTION
**Pull request by joaomoreno**

### CODE REVIEW

**Comment by gregvanl** [comment]
@joaomoreno Should this FAQ go in the specific setup\windows.md topic rather than in the general setup\setup-overview?

**Comment by joaomoreno** [comment]
Makes sense, can you move them?

**Comment by gregvanl** [comment]
Yep, will do.

**Comment by gregvanl** [comment]
Handled with https://github.com/Microsoft/vscode-docs/commit/26dc2b4c2465e76c3eaeddcabc9e0526b7dfa2f1

**Pull request closed without merging**
