### PR TITLE
New cpp debugger configurations

### PR DESCRIPTION
**Pull request by WardenGnaw**
Adding LoadSymbolInfo and RequireExactSource

@pieandcakes 

Note: Please wait on completing this PR till next week. For vscode-cpptools 1.26.0-insiders

### CODE REVIEW

**Comment by pieandcakes** [comment]
@mikeblome `solib` is the GNU term for `shared library`.

**Comment by pieandcakes** [comment]
Insiders should release next week.

**Comment by mikeblome** [comment]
A @pieandcakes @WardenGnaw just let @gregvanl know when this is ready to merge. Thanks!

**Comment by gregvanl** [comment]
@pieandcakes @WardenGnaw I see a 0.26.0 release yesterday October 15. Is this ready to merge?

**Pull request merged**
