### PR TITLE
Update codebasics.md

### PR DESCRIPTION
**Pull request by ksdavidc**
see https://github.com/microsoft/vscode/issues/105761

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @ksdavidc Thank you for submitting a PR. The current section on column selection describes the keybindings for the default mode. The Editor: Column Selection setting and command "Toggle Column Selection Mode" let users avoid the extra keybindings and directly use their mouse or navigation keys.
Perhaps you would like to add an H3 section describing the toggle mode? You could use https://code.visualstudio.com/updates/v1_43#_column-selection-mode as a starting point for the text.

**Comment by gregvanl** [comment]
Oops, didn't mean to close this PR.

**Comment by ksdavidc** [comment]
Wasn't intending on writing anything official as a bit above my usual pay grade...am I correct you are saying it would be helpful if I turned my revision into an h3, perhaps referencing the changelog you linked to as well as referring to the toggle command (which I didn't know about and may very well have been how I instantiated it via option v instead of ctrl v.  ). I haven't looked at the documentation enough to be sure I could maintain the style and standards for it. Furthermore, the menu and status bar items do not appear in my system (plugin conflict?), so I am not sure how to write about it or describe its behavior. Nonetheless, I have updated my branch using your text. Someone else might be able to improve it considerably.

**Comment by gregvanl** [comment]
@ksdavidc Thank you for working on this! I'll do a little editing and formatting but looks good overall.

**Pull request merged**
