### PR TITLE
Java tutorial:update videos accordingly

### PR DESCRIPTION
**Pull request by Eskibear**
Signed-off-by: Yan Zhang <yanzh@microsoft.com>

### CODE REVIEW

**Comment by Eskibear** [comment]
@nickzhums 
I removed some images which are not used in this docs, and updated the rest with latest UX.

**Review by nickzhums — APPROVED** [review]

**Comment by nickzhums** [comment]
LGTM - thanks!

**Comment by gregvanl** [comment]
@Eskibear I noticed that the jdk-configuration.png image is still used in the java-project topic.
I added it to docs/java/images/java-project with https://github.com/microsoft/vscode-docs/commit/007416aafb81794ee7e9039767f7998a62d99e58
Does this screenshot need to be updated?

**Comment by Eskibear** [comment]
> Does this screenshot need to be updated?

Yes, we changed UX of configuration page recently, see https://github.com/microsoft/vscode-java-pack/pull/791#issuecomment-958609869 .

@jdneo and I will create PR accordingly.

**Pull request merged**
