### PR TITLE
Update markdown.md

### PR DESCRIPTION
**Pull request by PeterWone**
Mention the existence of printing extensions that can automate the rendering of Markdown.

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @PeterWone Thank you for your PR and interest in the VS Code documentation.
Rather than add a mention of printing extensions in the Markdown preview section and short rendering walkthrough, what about if we add the VS Code Printing Free extension as a tile in the Markdown extensions section:

image

There is a space available as a previously called out extension has been removed from the Marketplace.

If this sounds good to you, I wonder if you could update the extension description in a few ways?
For example, "markdown" should always capitalized as "Markdown".
Also it would look better on the tile if "Fully rendered Markdown" came first.

**Comment by PeterWone** [comment]
Yes, that would be fantastic. Thank you for the opportunity.

Updating now to mention Markdown first in the extension description and generally capitalize “Markdown”.

**Comment by gregvanl** [comment]
Added the tile. It uses a live query to the Marketplace so when you update the extension description and republish the extension, it will be reflected on the tile.
I would be curious to hear how this mention affects your install count and user engagement. Maybe you can report back here after a month?

**Comment by PeterWone** [comment]
Fixed capitalisation of Markdown in all my docs and missed it in the extension description. I have bug fix going out next weekend, I'll fix it then.

**Pull request closed without merging**
