### PR TITLE
Add working hours for domain verification SLA

### PR DESCRIPTION
**Pull request by prashantvc**

### CODE REVIEW

**Comment by isidorn** [comment]
@prashantvc can you please explain the motivation for this PR?
@gregvanl and me feel like within 5 business days is precise enough. It is not like customers are counting hours.

@chgill-MSFT thoughts?

**Comment by prashantvc** [comment]
We have received the complaint lately about working hours of support. So, making it explicit

**Comment by isidorn** [comment]
I suggest to wait for more user feedback. We should not change docs just for one complaint. 
Let's assign to backlog until we gather more user feedback. Thanks!

**Comment by gregvanl** [comment]
Closing for now. We can reopen the PR if there is more user feedback

**Pull request closed without merging**
