### PR TITLE
New Docker extension setting name

### PR DESCRIPTION
**Pull request by bwateratmsft**
With https://github.com/microsoft/vscode-docker/issues/3539 we have changed the name of a setting in the Docker extension.

**Note:** Please hold off on merging this until we release Docker extension version 1.23.0, tentatively in ~~September~~ November?.

/cc @ucheNkadiCode

### CODE REVIEW

**Comment by bwateratmsft** [comment]
I made an update since we changed the setting name back to `docker.environment`.

**Comment by ghogen** [comment]
@bwateratmsft  Did this ship?

**Comment by bwateratmsft** [comment]
@ghogen We don't have an ETA yet but it's getting sooner. The big thing we're waiting on is changing to use the CLI only, that has finally made it to full-blown PR this week after months of being stuck on one thing or another.

**Comment by gregvanl** [comment]
@bwateratmsft There are also references to `docker.host` in the https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host.
For example in https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_a-basic-remote-example.
I'll merge and publish this PR but could you also update that topic in a follow-up PR? Thanks

**Review by gregvanl — APPROVED** [review]

**Comment by bwateratmsft** [comment]
Will do, thanks @gregvanl!

**Comment by chrmarti** [comment]
@bwateratmsft I think these should be all cases where we have this in documentation for Remote-Containers (renamed to Dev Containers). Let me know when there are any I miss. Thanks!

**Pull request merged**
