### PR TITLE
Replace `node-sass` with `sass` in the task example

### LINKED ISSUE #4667: node-sass is deprecated
https://code.visualstudio.com/docs/languages/css#_transpiling-sass-and-less-into-css

https://www.npmjs.com/package/node-sass is deprecated for almost a year. It doesn't support some of the newer features, like using `@use` instead of deprecated `@import`.

It should be possible to replace it in that task example with 

https://www.npmjs.com/package/sass  ( https://sass-lang.com/documentation/cli/dart-sass )

### PR DESCRIPTION
**Pull request by meowmeowmeowcat**
- Fixes #4667 
- Add a missing module so `gulp` won't throw errors

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @meowmeowmeowcat Thank you for submitting this PR. I'm still working through the tutorial flow and having issues with the gulp task. By and large, your contribution looks great but I want to make sure everything will be up to date once it is merged and published.

**Comment by meowmeowmeowcat** [comment]
Hi @gregvanl Can you describe what issues are you having with gulp task? Therefore, I can try to reproduce it and find the reason.

**Comment by gregvanl** [comment]
Hi @meowmeowmeowcat Sorry for the delay in getting back to this PR.
It looks like I need to install sass locally for the gulpfile.js build to work.
A global install of sass is required for the tasks.json build but a local install of sass is required for the gulpfile.js. Easy enough to add sass to the local install step `npm install gulp gulp-sass sass` but I want to play around a little more to make sure I understand how this works.
Did you find that you needed to `npm install sass` when you added `require (sass)` to gulpfile.js?

**Comment by meowmeowmeowcat** [comment]
Hi @gregvanl I don't think we need to `npm install sass` when I added `require (sass)` to gulpfile.js. Currently, commands in the docs (and commands I modified) work well for me.

**Comment by gregvanl** [comment]
I'll merge this and add the local install of sass. Thanks for being patient and taking the time to check the flow. Really appreciate your diligence. Thanks!

**Pull request merged**
