### PR TITLE
Add link to VS Code Community Discussions in API Overview page

### LINKED ISSUE #5433: Add a link to the new vscode discussions github repo
Recently, a [VS Code Community Discussions](https://github.com/microsoft/vscode-discussions/discussions) GitHub repo was created for extension authors to ask questions and learn about updates to the extension ecosystem.

It would be great if this link was added to the [Looking for help](https://code.visualstudio.com/api#looking-for-help) section on the Overview page of the API docs.

cc @daviddossett

### PR DESCRIPTION
**Pull request by hawkticehurst**
Resolves #5433

### CODE REVIEW

**Comment by hawkticehurst** [comment]
Seemingly can't assign reviewers so cc @gregvanl and @daviddossett

**Comment by gregvanl** [comment]
Before we go ahead with this, I'd like @digitarald to approve.

**Comment by hawkticehurst** [comment]
Oh yeah of course, happy to wait for that approval 😊

**Comment by daviddossett** [comment]
Looks like @isidorn had the same idea 😄 https://github.com/microsoft/vscode-docs/commit/93b5aa3de257ba0361f9155413709b3a5dfb516e

**Comment by isidorn** [comment]
I apologise!
I missed that there was a PR open. I just saw the issue and tackled it.
Sorry about that @hawkticehurst

**Comment by digitarald** [comment]
Same, thanks for jumping in @hawkticehurst. I think you filed the issue the same day we discussed this in our discussion sync!

**Comment by hawkticehurst** [comment]
No worries at all! 😊

**Pull request closed without merging**
