### PR TITLE
update some extension reporting guidlines

### PR DESCRIPTION
**Pull request by justschen**
- added documentation on contributing menu/issue reporter command

### CODE REVIEW

**Review by ntrogh — COMMENTED** [review]
@justschen I had trouble understanding how the different pieces fit together. I restructured the text a bit to how I think it works. Let me know if I didn't get it right.

It might be good to add a little more context about why you should use this approach versus the previous of contributing a `workbench.action.openIssueReporter` command.

**Comment by justschen** [comment]
@ntrogh gotcha! I like these changes, appreciate it! The main reason we wanted extensions authors to be aware of this was so:
a) extensions can now attach additonal data from the extension -> issue reporting 
b) removes many of the "Exension...: Report Issue.." commands from the command palette (like `Python: Report Issue` or `Azure: Report Issue`). There was a former limitation where authors _had_ to contribute the command to have access to templates and such, but adding the command directly to the palette will no longer be needed with the updates to the contribution point.

Not sure how we can best convey that?

**Comment by ntrogh** [comment]
@justschen I'll try and work something out.

**Comment by ntrogh** [comment]
@justschen I've made some changes to the section to try and better communicate the value prop. Feel free to update.

**Comment by justschen** [comment]
@ntrogh it looks good! thanks :D

**Review by DonJayamanne — APPROVED** [review]

**Pull request merged**
