### PR TITLE
Update guide to match latest vue version

### PR DESCRIPTION
**Pull request by MubarakSULAYMAN**

### CODE REVIEW

**Comment by MubarakSULAYMAN** [comment]
@microsoft-github-policy-service agree

**Comment by gregvanl** [comment]
Hi @MubarakSULAYMAN Thank you for working on this PR to update the Vue.js tutorial.
It looks good except that the PR is missing the new screenshot .pngs (for example, create-vue.png).
To add them, you'll need to enable Git LFS (Large File Storage) on your local repository. You can learn how to install and enable Git LFS by reading https://github.com/microsoft/vscode-docs?tab=readme-ov-file#cloning

**Comment by gregvanl** [comment]
Adding `don't merge` until missing images are added

**Comment by MubarakSULAYMAN** [comment]
@gregvanl, kindly review.

**Review by gregvanl — APPROVED** [review]
Thanks! 
Really appreciate you going through and updating this tutorial

**Comment by gregvanl** [comment]
Published live. Thanks again!

**Pull request merged**
