### PR TITLE
modifying FLASK_APP variable to be work with tutorial

### PR DESCRIPTION
**Pull request by ucheNkadiCode**
The current FLASK_APP environment variable errors because the webapp.py file is now found in the hello_app folder at this stage in the tutorial.

### CODE REVIEW

**Comment by ucheNkadiCode** [comment]
Hey I just wanted to make sure, did I do this correctly?
Are the minor edits able to be added without affecting the Python TOC or anything? 

Thanks

**Comment by gregvanl** [comment]
Hi @ucheNkadiCode, Your PR still has the new topics. Please submit a new PR after creating a new branch with just the initial tutorial correction. You can just copy your new files somewhere safe and remove them in your new branch.

**Comment by reconix23** [comment]
Hi to everyone, https://github.com/microsoft/vscode-docs/pull/3346/commits/5e78a7b1941ddf43dc06a6407cbdd04ddec3e2f1 seems to lack instructions for Powershell users using `$env:FLASK_APP` consider adding those, if possible.

`set FLASK_APP=hello_app.webapp` command doesn't work in Powershell 5.1 when copy-pasted. though autocomplete(via Tab key) does show `${FLASK_APP=hello_app.webapp}`

**Comment by gregvanl** [comment]
Closing in favor of https://github.com/microsoft/vscode-docs/pull/3359

**Pull request closed without merging**
