### PR TITLE
Added Azul Zulu to recommended OpenJDK distributions

### PR DESCRIPTION
**Pull request by HanSolo**
I think Azul Zulu should also be part of the recommended OpenJDK distributions. Thank's to Bruno Borges for the link to this repository.

### CODE REVIEW

**Review by brunoborges — APPROVED** [review]
LGTM

**Review by nickzhums — APPROVED** [review]

**Comment by nickzhums** [comment]
@HanSolo  actually I just remembered, the JDK we list here is based on alphabetical order, would you put the Azul in its corresponding location? thanks

**Comment by HanSolo** [comment]
Done

**Comment by nickzhums** [comment]
@HanSolo thanks! @gregvanl feel free to merge the PR when you have time, thanks!

**Comment by HanSolo** [comment]
@nickzhums I just installed VSC with the latest Coding pack for Java and it seems that Azul Zulu is there missing too. Bruno Borges told me that there is also the ability to create a PR to fix this too?

**Comment by HanSolo** [comment]
@nickzhums  Here is the screenshot: A276C0A6-943F-47D4-BBA5-8AC8BF2318C0

**Comment by nickzhums** [comment]
@Eskibear could you help to add this one to our list?

**Comment by HanSolo** [comment]
@nickzhums  @Eskibear Any news on this? Would be good to know if there is something in the making because we get questions from users that use VS Code and would like to install Zulu using the Java Coding pack.

**Comment by nickzhums** [comment]
@HanSolo We already opened a PR on our side to address it : https://github.com/microsoft/vscode-java-pack/pull/922

**Pull request merged**
