### PR TITLE
Sinemakinci/newcmakestatusbar

### PR DESCRIPTION
**Pull request by sinemakinci1**
Updating the docs to the new CMake status bar experience. 

Do not merge until CMake Tools ships - 11/15

### CODE REVIEW

**Review by twonpuncho23 — COMMENTED** [review]
Pull

**Comment by sinemakinci1** [comment]
@gregvanl can you review this week? we want to merge next week with release.

**Comment by gregvanl** [comment]
@sinemakinci1 The PR looks good. Could you delete the obsolete images?

**Comment by sinemakinci1** [comment]
@gregvanl removed!

**Comment by sinemakinci1** [comment]
@gregvanl  pinging for approval, goal is to merge tomorrow :)

**Review by gregvanl — APPROVED** [review]
Thanks!

**Comment by twonpuncho23** [comment]
merge

**Pull request merged**
