### PR TITLE
Fix LiveShare broken link

### PR DESCRIPTION
**Pull request by zcraber**
The LiveShare extension link was broken.

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @zcraber Thank you for noticing the broken link and submitting a fix.
There are several other places where the old URL is used. Would you like to search and fix them as well in this PR?

**Comment by zcraber** [comment]
> Would you like to search and fix them as well in this PR?

Sure, let me check. Glad to help.

**Comment by zcraber** [comment]
> 

@microsoft-github-policy-service agree

**Review by gregvanl — APPROVED** [review]
Thanks!
And thanks for the quick turnaround

**Pull request merged**
