### PR TITLE
Fix broken link to "TextDocument.isDirty"

### PR DESCRIPTION
**Pull request by hoovercj**
Put the hash in the correct place so the link works

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @hoovercj, this API document is auto-generated from vscode.d.ts. 
The broken link should be fixed in the vscode repo in the src\vs\vscode.d.ts. 
An easy fix if you want to submit a PR there.

**Comment by gregvanl** [comment]
Submitted https://github.com/Microsoft/vscode/pull/34329

**Comment by hoovercj** [comment]
Thanks for picking this up, it completely slipped my mind!

**Comment by gregvanl** [comment]
Sure, thanks for tracking down the issue!

**Pull request closed without merging**
