### PR TITLE
Add relativeFileNoExtension doc

### PR DESCRIPTION
**Pull request by unional**
For https://github.com/Microsoft/vscode/pull/28018

I added the debugging with transpilation section. See if you need to make some adjustements to the wordings.

### CODE REVIEW

**Comment by gregvanl** [comment]
Thanks!

**Comment by gregvanl** [comment]
Hi @unional, I reverted this commit. I don't believe there is a relativeFileNoExtension task.json or launch.json value. Are you sure your launch.json worked correctly?
Maybe you meant the fileBasenameNoExtension variable?

**Comment by unional** [comment]
It is in a PR as linked in the OP. And @isidorn ask me to create this PR

**Comment by gregvanl** [comment]
Oh, I see. I was too eager to merge. I'll wait for the other PR to go through and then put back your changes.

**Comment by isidorn** [comment]
@gregvanl exactly. I will let you know if we decide to merge in https://github.com/Microsoft/vscode/pull/28018 
I have also made a comment there that the docs should be consistent with the rest of the variables substitied, and not have a section of its own.

**Pull request merged**
