### PR TITLE
Update Copilot docs with pre-release info

### PR DESCRIPTION
**Pull request by bamurtaugh**
Update based on https://github.com/orgs/community/discussions/59964, as Copilot Nightly has been replaced by the pre-release version of the main GitHub Copilot extension.

@gregvanl @isidorn @sandy081 let me know if you have any feedback on the updates here, especially on the image and link I added. I'm debating linking to https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions to help users understand pre-release extensions, but since the article is extension publishing focused, I linked to the release notes on pre-release extensions to start.

### CODE REVIEW

**Comment by gregvanl** [comment]
@bamurtaugh That is a content gap that we don't have a mention of pre-release extensions in the user guide Extension Marketplace article. Reaching back and linking to the release notes mention seems the best option for now.
I'll update docs/editor/extension-marketplace and update the links later.

**Comment by gregvanl** [comment]
I switched the release notes URLs to be absolute as I'm a little unsure how the link preprocessing would work for relative paths.
Again, these links will be updated shortly

**Review by gregvanl — APPROVED** [review]
Thanks!

**Review by rzhao271 — APPROVED** [review]

**Comment by isidorn** [comment]
This looks great, thank you @bamurtaugh!
I full text searched for "copilot nightly" and I found that we still mention it in the 1.77, 1.78 and 1.79 release notes.
Should we update those as well? Since a search engine might drop users on those older release notes even if they are not the official docs.

**Comment by gregvanl** [comment]
I thought we wouldn't update the release notes since they are a point in time and we usually leave them as they were when we published them. 
However, I just took a look at the code.visualstudio.com page views for 1.77 (10K), 1.78 (68K), and 1.79 (187K) in June and they are still pretty high so I think it makes sense to update those notes.

**Comment by bamurtaugh** [comment]
Thanks @isidorn for the feedback and @gregvanl for the data! I'm happy to open a PR to update them, but @gregvanl let me know if you already plan to incorporate these changes in your vnext updates.

**Comment by gregvanl** [comment]
@bamurtaugh I planned to put together a PR with a couple of follow up items tomorrow and I can include the release notes changes as well

**Comment by isidorn** [comment]
Thanks Greg 👏

**Pull request merged**
