### PR TITLE
Clarify "compute"

### PR DESCRIPTION
**Pull request by jswhisperer**
docs typo compute to computer

### CODE REVIEW

**Comment by ntrogh** [comment]
@gregpalaci Thanks for contributing. In this instance we're using "compute" as a term to refer to the broader category of compute  resources. So, closing this PR.

**Comment by gregpalaci** [comment]
No worries, I feel like it's the wrong wording though. Perhaps "Instance" would make more sense.
It's a verb, it feels very awkward in this context, my own compute would be more like your own thoughts or reasoning, rather than a reference to a "compute" I owned like machine or cloud etc.

Food for thought.

**Comment by ntrogh** [comment]
Maybe we can settle on "compute instance"?

**Review by ntrogh — APPROVED** [review]
@jswhisperer Thanks for updating and putting effort in making our docs better! Appreciate it.

**Pull request merged**
