### PR TITLE
Update .NET Core -> .NET

### PR DESCRIPTION
**Pull request by jamesmontemagno**

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @jamesmontemagno Thanks for the PR!
Should we also update https://code.visualstudio.com/docs/languages/csharp?
Looking at https://dotnet.microsoft.com/en-us/download, it appears that we still say "ASP.NET Core", is that correct?

**Comment by jamesmontemagno** [comment]
@gregvanl let me do it in this PR..

It is still "ASP.NET Core".... but ".NET Core" is now just ".NET" :)

**Comment by jamesmontemagno** [comment]
Updated @gregvanl

**Comment by gregvanl** [comment]
Thanks!

**Pull request merged**
