### PR TITLE
replace deprecated dev extention

### PR DESCRIPTION
**Pull request by nallon**

### CODE REVIEW

**Comment by cadamini** [comment]
Missing description. The originally linked pages contains:

> New official vue editor support: Volar
> VSCode extension: https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by cadamini** [comment]
@gregvanl easy fix/approval?

**Comment by gregvanl** [comment]
Hi @cadamini The tutorial will need to be reviewed for possible new UI and workflows from the new Volar extension.
I don't think this can be merged as is.

**Comment by cadamini** [comment]
You are right, lines 60 and below refer to the old extension. 

@nallon any plans to update this, too?

**Comment by nallon** [comment]
Not at the moment.

**Pull request closed without merging**
