### PR TITLE
improved screenshots and added 'Markdown Preview' button instruction

### PR DESCRIPTION
**Pull request by potateros**
Improved some screenshots to make it clearer, as well as adding the 'Open Preview to the Side' button instruction to reactjs-tutorial.md

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @potateros Thank you for your interest in the VS Code documentation and taking the time to submit a PR. We prefer to use the default dark theme for screen shots so that new users will see familiar coloring and highlights.

**Comment by potateros** [comment]
Thanks for reading through my PR @gregvanl , but I don't understand, I thought I had been using the default dark theme? It is the 'Dark+ (default dark)' theme right? Sorry, this is my first PR, and I'd love to help contribute to something that had benefited me greatly :smiley:

**Comment by gregvanl** [comment]
Hi @potateros Here's what Dark+ should look like (blue links, no tab underline).

image

Perhaps you have some non-default settings or extensions installed. Screenshots should be with default settings and no extensions installed (code --disable-extensions)

**Comment by potateros** [comment]
Ah, got it! Will submit one with default and no extensions. Thanks!

**Pull request closed without merging**
