### PR TITLE
{Work in Progress} Update faq.md 

### PR DESCRIPTION
**Pull request by snow8gaia**
Solving some FAQ issues so users don't have to waste time, think its weird. And developers can develop code.

### CODE REVIEW

**Comment by JonasT** [comment]
maybe someone of the vscode team could fill in "It is unclear at this stage" with an exact & complete description of what the difference is? would be really nice to have finally have some voices heard about our concerns with the lack of transparency and misleading statements regarding the two versions

**Comment by snow8gaia** [comment]
I made a huge mistake in the PR.

**Comment by snow8gaia** [comment]
**Fixed the huge mistake.**  Found some more. 
And then, the CLA bot decided to showed up; signed the CLA.

----
<details>

[](Testing msftclas complexity)
<p></p>

</details>

 is @msftclas overworked?

**Comment by JonasT** [comment]
@snow8gaia you appear to be making up statements here in place of Microsoft developers.

Some of these statements seem completely without value until a VS code dev actually says them, like `We are dedicated to resolving this as soon as possible`. Is anyone dedicated to that?

Even worse, why write something like `TL;DR - We started out with this model, thought it would be open-source friendly.` when you don't even know what they thought? Why make that up?

I would love to hear some of these things, but until we've had that discussion what you're doing here seems more like a work of wishful fiction than an accurate, useful text. *If you got sources for these statements then I take everything back and apologize for the interference.* Also, obviously that's just my two cents, I can't accept or reject anything in this repo I'm just a bystander of sorts

**Comment by snow8gaia** [comment]
The CLA. It had two pages. Was definitely useless. I signed it because I am ~~stupid sometimes~~ more interested in ensuring that nobody else gets deceived

----

**Comment by snow8gaia** [comment]
@JonasT Thanks for feedback in https://github.com/Microsoft/vscode-docs/pull/2431#issuecomment-470627908. 

right now, this PR is like a test for whether or not there is any interest from the devs. Also, feel free to create a new PR to update the FAQ if you want to. And either use this PR as base, or start fresh.

**Comment by snow8gaia** [comment]
@JonasT Thanks for feedback in https://github.com/Microsoft/vscode-docs/pull/2431#issuecomment-470627908.

right now, this PR is like a test for whether or not there is any interest from the devs. Also, feel free to create a new PR to update the FAQ if you want to. And either use this PR as base, or start fresh.

**Comment by gregvanl** [comment]
Hi @snow8gaia  Unfortunately your PR was closed during our shrinking of the vscode-docs repo. You will need to re-clone vscode-docs, reapply your changes and submit another PR. Sorry for the inconvenience. The repo is now much smaller and you can use Git LFS if you like. See CONTRIBUTING for details.

**Pull request closed without merging**
