### PR TITLE
Update unity.md

### PR DESCRIPTION
**Pull request by lukaszunity**
Added Debugger for Unity extension text and links.

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi Lukas, I'm not ignoring your pull request.  I just need to do a little review of the Unity topic. Thanks for your patience.

**Comment by lukaszunity** [comment]
That's fine ;-) Since I opened this PR, the author of the VS Code plugin for Unity has also updated his plugin to support the debugger extension Unity has released VS Marketplace

http://forum.unity3d.com/threads/vs-code-unity-debugger-extension-preview.369775/page-2#post-2481118

**Comment by lukaszunity** [comment]
Hi. Maybe @reapazor has some comments to this PR, since his VS Code plugin has been updated this I opened this PR.

**Comment by reapazor** [comment]
Well the plugin currently installs the extension if the user wants, theres a nice big button. Not sure if you want to include that in the documentation.

**Pull request merged**
