### PR TITLE
Noting NPM install doesn't support `open`

### PR DESCRIPTION
**Pull request by vike2000**
https://github.com/microsoft/vscode-remote-release/issues/5957#issuecomment-999355431

### CODE REVIEW

**Comment by gregvanl** [comment]
Hi @vike2000 Thank you for submitting a PR and your interest in the VS Code documentation.
I wonder if you could be hitting the same issue seen in https://github.com/microsoft/vscode-docs/issues/5041?
The `open` command should be supported by the devcontainer CLI.

**Comment by vike2000** [comment]
As I understand it from [the issue comment](https://github.com/microsoft/vscode-remote-release/issues/5957#issuecomment-999355431) I linked in the commit message / [PR comment](https://github.com/microsoft/vscode-docs/pull/5084#issue-1097266557), the executable `devcontainer`'s suport for (sub)command `open` depends on with which method one installs it:
1. In vsCode, using command `Remote-Containers: Install devcontainer CLI` (id `remote-containers.installUserCLI`), `devcontainer` supports `open`.
2. In a CLI, using `npm list -g @vscode/dev-container-cli` (I haven't tried without `-g`), `devcontainer` doesn't support `open`.

> [at-mention] There are two ways to install the CLI: As part of the Remote-Containers extension and as an NPM package. Currently the NPM package does not support `open` because it lacks the association with your VS Code install. This feature request is about improving that.
> 
> When you use the CLI installed as part of Remote-Containers, the `open` command is available. (If it is not, it would be a bug.)

  _\- @chrmarti in https://github.com/microsoft/vscode-remote-release/issues/5957#issuecomment-999355431_

(I made a comment there, asking parenthetically and was pointed to this repo.)

Thanks @gregvanl for mentioning #5041.
#5041 refers to the docs saying "the output of `devcontainer --help` lists a command named `open`", compares that with ***an*** installation not listing the `open` command, and ends to conclude that "`open` is no longer available." (The installation is only specified as being on Ubuntu, but could very well have been made with `npm`, in which case my PR could've aided the understanding.)

When I install using method 1 above, `devcontainer` still lists (and supports) `open`, but when I installed it with method 2 it doesn't list (nor does it support) `open`.
Thus, _@chrmarti in https://github.com/microsoft/vscode-remote-release/issues/5957#issuecomment-999355431_ agrees with the behaviour I observe while the conclusion in #5041 (interpreting it as a general regression) seems amiss.

**Comment by vike2000** [comment]
Oh, looking again, I realize @chrmarti answers the same person - @ManfredLange - in https://github.com/microsoft/vscode-remote-release/issues/5957#issuecomment-999355431 as @gregvanl does in the issue #5041 mentioned previsouly.
Assuming this is two sides of the same issue, I understand it in #5041 as that @ManfredLange solved the issue https://github.com/microsoft/vscode-remote-release/issues/5957 by restarting Windows - seemingly what I would call the host - while mentioning installing `devcontainer` in Ubuntu - I'm guessing the system virtualized within the host.
Forgive my confusion regarding this.

To be clear, I still think my PR is accurate and adds to the understanding regarding the current workings.

**Comment by gregvanl** [comment]
Thanks! And thanks for tracking this down across various repos

**Pull request merged**
